### ISSUE TITLE
[Enhancement]  1.8 Integration

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#103]
We use pvpArena in 1.8 Spigot Server. 

it's working fine. Somebody can add 1.8 feature like /title and spectator mode. 

Tks

**Comment by Oruss7** [comment]
may be an extern developer can help plz ?

**Comment by slipcor** [comment]
yeah I will definately not be adding anything like that, until there is an official bukkit version that has 1.8 feature. They have not done this in a year, and I don't expect them to do. If someone does please code it in a way that it works on 1.7.9 and I will probably merge pulls!

**Comment by slipcor** [comment]
alright I will look into this :) spectator mode is done, btw! the module "Spectator" does exactly what you think it does :)

And about the titles... what should this contain? The "goal" messages about people claiming stuff, killing someone, winning, losing? I will have to experiment with the values I can use there, because I have NO clue about how this works. It will take some time but will be awesome.

**Comment by Oruss7** [comment]
Generally, titles are used for display 3, 2, 1, go !

**Comment by slipcor** [comment]
Alright, this is next up, can we talk over skype or similar about how this is supposed to work on the server administrator end? If you are on IRC somewhere, join #pvparena :D

**Comment by Oruss7** [comment]
We have a Teamspeak 3 server. I ask my friend.

**Comment by slipcor** [comment]
oh sorry I missed you, I took a nap xD

**Comment by Oruss7** [comment]
lol, okay, no problems

**Comment by slipcor** [comment]
v1.3.2.97 - add Titles API hooks, documentation will follow

I am committing a new module, Titles :) defaulting to your things, counting, starting, winning, losing :)

**Comment by Oruss7** [comment]
Titiles work. But need to add manually ti install.yml ?

**Comment by slipcor** [comment]
no, I fixed the install.yml yesterday, it should/will be updated on server start :)

It is downloaded from my server :)

if it doesnt work: http://pa.slipcor.net/install.yml
