### ISSUE TITLE
[Bug] Arena spectate offsets location by .5 blocks.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#104]
When typing ```/pa <arena> Spectate``` to get to the spectator location, the spawn point teleportation is offset by 1/2 a block. The config coordinate is correct, the teleportation is wrong.

**Comment by slipcor** [comment]
https://github.com/slipcor/pvparena/blob/master/src/config.yml#L8

It's a fix to prevent people to get teleported inside the ground, or fall to the ground due to lag. Feel free to set this to 0.0 and experiment ;)

**Comment by mibby** [comment]
@slipcor What? You're alive? I was just creating this ticket for the heck of it to reference if you ever came back. :O

**Comment by mibby** [comment]
Anyways, the offset is by axis, not height.

**Comment by slipcor** [comment]
oooh well that is absolutely intentional then. The information always will be block-location, and then you get teleported to the middle of that very block you selected. So if you WANTED to be on a block edge, that is not possible :(

And yes, I am very alive... Trying to enjoy life without minecraft. I still did not have time to recover from what I assume is/was a burnout - but who cares :P

**Comment by mibby** [comment]
Ah, well that's good to hear. I'll always be here though if you ever do decide to start development again for minecraft related stuff. PVPArena for life - no suitable replacement. <3

Regarding the orientation, I'm trying to have the coordinate be in the center of a block but when teleporting, it is offset by .5 - on the corner. Essentially not on the block I have the coordinate set to.

**Comment by slipcor** [comment]
Sorry to hear that. I have no idea why that is. Maybe the spectator spawn somehow has the .5 information already and you can remove that manually OR set it ON the corner to the negative X and Z side?

**Comment by mibby** [comment]
I'll probably have to offset it manually in the config by adding .5. This is the exact location.

```
  spectator: world,774,72,8834,-269.8243408203125,3.9000020027160645
```

So it should be perfectly centered normally, ignoring rotation angle. But the teleportation offsets it.

**Comment by slipcor** [comment]
I don't think that this will work, as it SHOULD read integers, but try it - with backup ;)

**Comment by mibby** [comment]
I'll just live with the offset I suppose. :(

**Comment by mibby** [comment]
I lied. I can't live with the offset. It is too annoying and just doesn't seem right. Could the Y offset setting  be broken in the code base and be offsetting the wrong axis?

**Comment by slipcor** [comment]
I highly doubt it. But maybe. You are faster to find out the answer to that. The code should be in arena.tpToCoordname or similar

**Comment by mibby** [comment]
Could it be caused because 0.5 is being added but not specified specifically as Y axis height?

Here
https://github.com/slipcor/pvparena/blob/ef55d5b546f8a62c879b72328df873f20abaf9b4/src/net/slipcor/pvparena/managers/SpawnManager.java#L424
Or here.
https://github.com/slipcor/pvparena/blob/ef55d5b546f8a62c879b72328df873f20abaf9b4/src/net/slipcor/pvparena/managers/SpawnManager.java#L503

**Comment by slipcor** [comment]
As I said. The system saves block locations (integers) that translate to block borders. I added 0.5 so you stand on the block and not on the edge

**Comment by slipcor** [comment]
If there is an issue with that, fix it :D

**Comment by slipcor** [comment]
Here you go, mibby : 

v1.3.0.555 - add x-offset and z-offset, so one can change the default behaviour of putting ppl on the middle of a block

I will upload this to http://pa.slipcor.net/pvparena.jar - you can test it in 5 minutes!

**Comment by slipcor** [comment]
note to self: the solution to this is allowing precise spawns, not always offsetting. Will be done in a spawn system rewrite ^^

**Comment by mibby** [comment]
For future reference - related.
https://github.com/slipcor/pvparena/issues/126

**Comment by slipcor** [comment]
this might work : v1.3.1.28

**Comment by mibby** [comment]
Manually setting an offset with ```/pa [arena] spawn [spawnname] offset x y z``` works. Can have spawns centered between 2 block wide hallways now. :)
