### ISSUE TITLE
[Bug] [Module - ColorTeams] Scoreboard nametag not reverting to the original (before entering arena) when leaving the arena.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#109]
Player scoreboard nametag colors are not persisting / reverting back to their former color when leaving an arena. For example, a player with a green nametag joins an arena. His nametag changes to blue for being in the 'free' team. (Or red if on the red team in CTF for example.) When he is killed, his nametag reverts to white when put into spectator. When he leaves the arena, his nametag should revert back to his original former color (green), but doesn't. It remains white.

Error for reference. http://paste.ubuntu.com/14247880/

```
14:06	slipcor	well ok I need to check this, I need to find out how exactly you add someone to a team properly, maybe I forgot something
14:06	slipcor	maybe I even have to re-construct the team on the fly?
14:06	slipcor	I have no idea
14:07	slipcor	well no, its an NPE because the backup team returns null
14:07	slipcor	so the scoreboard is OK, but the team is not
```

**Comment by mibby** [comment]
Issue still present. Pesky former scoreboard nametags are being lost and displaying white only. Need to relog for proper display to occur again.

**Comment by slipcor** [comment]
can you check if the latest modules has fixed it? I removed the TagAPI thingie and switched something around

**Comment by mibby** [comment]
This issue still occurs. Nametags display white after players are kicked out of the arena on end. Have to relog to get the former colors back / see people with colored nametags again. 

For what it's worth, this issue doesn't seem to happen in the MobArena. Players who join the MobArena, their nametag turns white. It also remains white when spectating / on arena end (death). But when a player leaves MA when in the arena or at the spectator location (/ma leave - brought there on death because the arena doesn't kick players out when everyone dies), nametags revert back to their former color for all players correctly.

**Comment by slipcor** [comment]
I have a suspicion - I do the reset on player leave AND on player reset, while the reset should be enough and actually... when doing it on both times it will reset them to white, obviously :P so could you check out the latest Modules build #78? This attempts to fix it

**Comment by mibby** [comment]
@slipcor This issue still occurs as of PVPArena v1.3.2.110 and ScoreBoards v1.3.2.106.

Before joining an arena. In F1 view (scoreboards don't hide when in F1)
![link13](http://i.imgur.com/IbUOUld.png)

Joined an arena and started the game. Then promptly left.

Post arena game, in F1 view. (Scoreboard nametag is missing)
![link14](http://i.imgur.com/r5bPYQJ.png)

In non-F1 view, you can see it is a normal white nametag. (non-scoreboard)
![link](http://i.imgur.com/sSuXbrL.png)

Relogging fixes the issue and shows the correct colored scoreboard nametag.

**Comment by mibby** [comment]
"System.identityHashCode says that ArenaPlayer instances are killed between joining and leaving"
http://paste.ubuntu.com/16384107/

**Comment by mibby** [comment]
Fixed inhttps://github.com/slipcor/pvparena_modules/commit/ea649cd6cc47544945abfaea031befd3c1a3c076
