### ISSUE TITLE
[Bug] Clarify misleading error in general debug log when requesting score to win.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#112]
Example being from this error log. http://paste.ubuntu.com/14246378/

```
[INFO] [PA-debug] 801 Domination is setting error to: 100
```

As it isn't really an error (?) and doesn't specify what exact is requesting it to be set to 100 or why.

Also, ``` 15.12.28 12:54:17 [INFO] [PA-debug] 606 null arena ``` not referencing to anything?

**Comment by slipcor** [comment]
"null arena" will be changed to "not part of an arena" - it's basically when something is spawned somewhere but it's not part of an arena (region)

**Comment by slipcor** [comment]
v1.3.1.29 - address github issue #112

I just removed the message being shown if the return value is parse-able to a number, which only happens if Lives are involved. No way to debug this IN the method (i.e. where the call came from)
