### ISSUE TITLE
[Suggestion] Add compatibility support for McMMO to disable ability benefits inside battlefield regions.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#113]
A config option to enable/disable mcmmo abilities/benefits/leveling in arenas for compatibility would be nice. To prevent users with level 100 sword skill from doing more damage to others or someone with acrobatics level 1,000 from taking fall damage / having a dodge chance. 

I currently disable all activation abilities and pvp modifiers in mcmmo, but something with more compatibility to prevent leveling and passive non-pvp ability benefits in arenas would be nice. If not, all's fine. :)

**Comment by slipcor** [comment]
please use TempPerms for that - unless you really want to have this region based??? This ties back to the issue we talked about .... plugins like worldguard handle this better, Region based Permissions really are a pain, and my implementation would be inferior to established plugins
