### ISSUE TITLE
[Suggestion] [Goal - King of the Hill / Domination] Visual representation for remaining claiming time.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#117]
I think there should be a better visualized representation for how much longer someone has to go for claiming a flag. This can be used for other goals as well that rely on anything time based.

You could use their experience bar at the bottom and fill that up, a scoreboard timer/fill bar, a hologram  (1.8+), or a small boss bar at the top or bottom of the screen that fills.

**Comment by Oruss7** [comment]
or experience bar

**Comment by slipcor** [comment]
How about we use the BOSS BAR? :D there will be easy API support for this in Spigot 1.9 :)

**Comment by slipcor** [comment]
even with colors ;)

**Comment by mibby** [comment]
Boss bar could work great, especially now that boss bars are standalone in 1.9 (if I recall correctly, no longer needs a boss entity spawned). Could also use an actionbar title as well for something less 'in your face'.

**Comment by slipcor** [comment]
this actually was easy and fun to implement :O
