### ISSUE TITLE
[Bug] Arena does not show up in-game if it is not added to the shortcut list.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#121]

**Comment by slipcor** [comment]
Well but that's the reason you add shorcuts, isn't it? Using them only makes those short-cut-ed arenas visible, actually it only should show the shortcut and no individual arena, right?

**Comment by mibby** [comment]
Confirmed fixed. https://github.com/slipcor/pvparena/commit/1b0245bc43b716212c40ff816b211cf4004ef7c7
