### ISSUE TITLE
PA STATS command, NULL value

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#122]
I test some commands like 
` pa stats hehhhq`

And that display valid type incluing `NULL` ?!

I test `pa stats NULL` and result some strange things...

**Comment by slipcor** [comment]
hmm yeah I will fix this xD

**Comment by slipcor** [comment]
actually there is nothing to fix. Just, it is called NULL ... where it should be called PLAYERNAME

**Comment by slipcor** [comment]
I'll fix this by removing the NULL display
