### ISSUE TITLE
[Enhancement] Expand in-game clock countdown support.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#124]
Support for any number of defined time instead of pre-determined numbers.

Right now it supports 1, 2, 3, 4, 5, 10, 20, 30, and 60. You should allow for it to start and countdown at the user's defined amount of time. For example, starting/respawning in 42 seconds. You don't have to spam chat with a number countdown, just have the initial number begin counting down from their defined value and output in chat that starting number. When the time passes over a pre-determined number's output, display it.

Example. 

```
The game will start in 42 seconds.
* 12 seconds pass*
Starting in 30 seconds.
*15 seconds pass *
Starting in 15 seconds.
* 5 seconds pass*
10..
5..
4..
3..
2..
1..
```

Also support for custom countdown tiers for users that want to change the language at a specific number? Or allow for it to spam chat with a greater countdown?

**Comment by slipcor** [comment]
Hmm yeah I'd have to change the implementation there I guess.... this requires all modules to adapt to that, unless I find a backwards compatible way :/

**Comment by slipcor** [comment]
@mibby so ... would you want to set this arena wide then, for all types of countdowns? TimedEnd, relay runnable, we have so many timers or do we need one config section (containing the "wanted messages") for each timer type? that would blow up the config even more :/

**Comment by mibby** [comment]
Hmm. Well this would be solved by two relatively simple things, no?

1) Use the defined time the player set as the initial starting time to count down from, then output that defined time in chat as the initial starting message. Then follow the logic for the remaining time output display? Example;

User wants it to start counting down from 13 seconds. So have the arena output 'The game will start in <defined> seconds.' and start the countdown internally from that time. Then follow logic for remaining chat output when it passes over a time milestone. 'Starting in 10 seconds.' 5.., 4.., 3.. etc.

2) Add language strings to the 'time milestones', similar to TIMER_STARTING_IN? 
https://github.com/slipcor/pvparena/blob/15b5a2e4a0e9aec4ef9928f5a10e84e16dbd9069/src/net/slipcor/pvparena/runnables/ArenaRunnable.java#L28

For example;
- TIMER_STARTING_IN
- TIMER_REMAINING_60MINUTES
- TIMER_REMAINING_50MINUTES
- TIMER_REMAINING_40MINUTES
- TIMER_REMAINING_30MINUTES
- TIMER_REMAINING_20MINUTES
- TIMER_REMAINING_10MINUTES
- TIMER_REMAINING_5SECONDS
Etc. So each countdown milestone could be customized to your liking, or even removed if you didn't want a specific number to output due to spam?

**Comment by slipcor** [comment]
And again, you realize we have like 10 timer strings? So for each of those strings allow/add 10 individual things for each time? :(

**Comment by slipcor** [comment]
I am pushing this to 1.3.3 - I am planning to rewrite the modules AFTER 1.3.2 is done, so that the modules have their own configs. So by doing that I can add another module that will have individual config maps for each timer. Does that make sense, @mibby ?

**Comment by mibby** [comment]
I suppose? But you should still support starting from the defined timer users set. I.e. 1) listed above.

**Comment by slipcor** [comment]
look for "time_intervals" in the language file [for global messengers] and the arena configs [for arena related messengers] ;)
