### ISSUE TITLE
[Suggestion] Support for removing player particle trails when entering an arena and replacing it when leaving, similar to scoreboard nametags.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#125]
Is it possible to remove player particle trails for when they join an arena and replace it back when they leave the arena, similar to how scoreboard nametags is handled? This would allow for some players with obnoxious particle trails to not have them when running around in an arena, or to allow it to be disabled for when users forget to manually turn it off when playing gamemodes that require them to be stealthy.

The particle trails plugin I use.
https://www.spigotmc.org/resources/trailgui.1091/

Could have a module to add a particle trail to a class/team, similar to how ColorTeams module is used to colorize and revert the scoreboard name. That way you could use the module to either set everyone/specific teams to use a specific particle effect or have none set to remove any if they had any before going into the arena. Or just further extend the betterfight/betterclass module features?

**Comment by slipcor** [comment]
No, I'd rather you use the EventActions module to add commands which do that. If 50% of my users report that they use this specific plugin it might be worth an addition, but we will never get to v2.0 if I add support for every possible individual plugin :) <3

**Comment by mibby** [comment]
That's fine. This suggestion can be safely ignored. :)
