### ISSUE TITLE
[Enhancement] [Module - SpawnOffset] Allow for individual spawn points to be offset in value.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#126]
A module to allow defined spawn points to be offset. Would be useful for getting 2x2 block hallway spawnpoints centered in the corners of the blocks instead of dead center in the middle of a single block. For precision locations, getting the spawn point exactly where you want it.

Something like
```
SpawnOffset:
    - spectator: 0.5,0,0.5
    - spawn2: -0.5,0,0.5
```

**Comment by slipcor** [comment]
I decided to not do this in a module. It would be really hard to make it sane this way.

Adding another layer of module checks at this point only makes teleporting worse :D
