### ISSUE TITLE
[Bug] Arena joining does not continue when one of the configurations in the shortcut list is disabled.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#127]
E.g.

```
shortcuts:
  CTF:
  - CTF
  - CTF2
  - CTF3
  - CTF4
  - CTF5
  - CTF6
```

Players join with the command /pa CTF. If CTF 4 is disabled, eventually people playing CTF, it will try to load that map. Saying the arena is disabled. Shouldn't it skip over disabled arenas and move onto the next enabled one to play?

**Comment by slipcor** [comment]
Yeah it should

**Comment by mibby** [comment]
Confirmed fixed. https://github.com/slipcor/pvparena/commit/3e91a51e12feb4455d545714e87de9357fb7e8ad
