### ISSUE TITLE
[Suggestion] Expand rounds module support.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#128]
Allow for rounds to repeat the same goal/map configuration and switch sides.

Example being a CTF type gamemode with attackers and defenders. Every round, switch sides.

Also allow language to output current round and number of rounds total. Example;

```
Round 2 of 4.
```

```
Round 2/4
```

**Comment by slipcor** [comment]
Sorry to say but I think the side switch thing is too big of a change right now. The rounds system has no idea about possible teams and/or player configurations and actually never enforces those. Adding this is probably for another version xD 1.3.3 :)

About the round display, sure, that makes sense! You know, the only issue might be that people are not IN the arena when it is updating the round, but I will try to fix this :)

**Comment by slipcor** [comment]
No. I think I have to push this to 1.3.3 - the whole round system does not make sense as-is. It only ever advances if you have shortcuts enabled or if you have an EndTimer running that ends the game.

I have to rethink this system and make sure it is implemented in a sane way

**Comment by mibby** [comment]
Closing ticket. I personally no longer use this module so closing to reduce the possible work burden to implement / fix. Feel free to re-open if this is something you do want to implement.

Rounds was quite buggy but it's been years. It would probably be better to consider implementing as a core function in any type of rewrite so you could have games with rounds that switch gamemodes or flip sides.
