### ISSUE TITLE
[enhancement] Put Schematics on sub-folder "schematics"

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#129]
Please instead of all in plugin mixin with config files ='(

**Comment by slipcor** [comment]
well there are just 3 config files? This might be for 2.0 when everyone starts from scratch anyways... changing this  behaviour now will probably link to broken servers

**Comment by Oruss7** [comment]
add a config : schematic folder ? may be a good solution if we want put schematics on the worldedit schematic folder

**Comment by slipcor** [comment]
hmm that might work. I have to make it clear how to use it though. Let's say the standard folder would be what... /plugins/pvparena ? so you can change it to /plugins/WorldEdit or whatever it is?

I hope PVP Arena can access this folder. But that's your problem xD I will add this later or tomorrow :) I got a ton of issues to fix/add/think about :D And this is not as quick as you think. I have to actually get the plugins and verify it works, I cannot just assume it does.

**Comment by slipcor** [comment]
I hope we didnt break anything :) please check latest modules v1.3.2.94 !

**Comment by Oruss7** [comment]
yeah ! i try

**Comment by Oruss7** [comment]
I will try https://github.com/slipcor/pvparena_modules/pull/15 after work and i close if ok
