### ISSUE TITLE
[Bug] '/pa debug all' is creating debug files for all arenas instead of only a general log and a log file for arenas active.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#130]
Example of a debug log from an arena that wasn't active.

CTF
```
15.12.31 10:57:03 [INFO] [PA-debug] 439 PAExitEvent
15.12.31 10:57:15 [INFO] [PA-debug] 96 PAExitEvent
15.12.31 10:57:25 [INFO] [PA-debug] 96 PAExitEvent
15.12.31 10:57:30 [INFO] [PA-debug] 58 resetting arena; force: true
15.12.31 10:57:30 [INFO] [PA-debug] 58 resetting player manager
15.12.31 10:57:30 [INFO] [PA-debug] 58 fighting : false
```

Liberation
```
15.12.31 12:43:06 [INFO] [PA-debug] 726 PAExitEvent
15.12.31 12:43:12 [INFO] [PA-debug] 642 PAExitEvent
15.12.31 12:43:12 [INFO] [PA-debug] 645 PAExitEvent
15.12.31 12:43:31 [INFO] [PA-debug] 396 PAExitEvent
15.12.31 12:43:37 [INFO] [PA-debug] 297 PAExitEvent
15.12.31 12:43:37 [INFO] [PA-debug] 303 PAExitEvent
```

**Comment by slipcor** [comment]
could this  be related to the arena voting thing which basically DOES activate and deactivate arenas?

**Comment by slipcor** [comment]
@mibby ?

**Comment by mibby** [comment]
I'd be willing to test a 'nasty version' to find out why these debug files are being created. I'm not sure exactly what you mean by 'arena voting thing', as I have no such feature in regards to voting for arenas.

**Comment by slipcor** [comment]
I think I found it. The Listener sometimes stays on even though the arena is deactivated. I am hesitant to kill the listener, I need to cross check if that can break things, I did make sure that the module is actually running and the Exit Event is of that arena, if not, the event is skipped.

v1.3.2.106 - [ScoreBoards] - stop triggering debugs on inactive arenas!

latest modules should have the new version :)

**Comment by mibby** [comment]
Seems to be fixed now. Working as intended, no debug log for all arenas when joining a specific one.
