### ISSUE TITLE
[Bug] [Goal - Time] Timedend does not properly specify winner in score lead.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#131]
Examples. 

Timedend in CTF after 15 minutes. Winner is chosen by which team has scored the most point.
Timedend in FFA. Winner is chosen by who has the most kills (or lives, depending on score goal used?)
TDM - Winner by team with most kills/lives.

**Comment by slipcor** [comment]
isn't this the case?? it should be :P please check! invite me ;)

**Comment by slipcor** [comment]
@mibby :)

**Comment by mibby** [comment]
Allowing timedend to pick a winner based on their score / who is in lead is not currently possible I don't believe. I only see;
```
  time:
    timedend: 1200
    winner: none
```

**Comment by slipcor** [comment]
yeah but if none is selected it should  happen as follows:

https://github.com/slipcor/pvparena/search?utf8=%E2%9C%93&q=timedend

Hope that link works. Every goal has a "timedend" calculation built in, sending their own score, which is being tallied and at the end of the day, the timed end checker does sum up all "points" and calculates the winner, or winning team :)

**Comment by mibby** [comment]
Ah, I'm a bit confused. So for timedend to actually forcefully end the arena but pick a winner, I would just leave the 'winner:' field blank? For example ```winner: {}```? As it is used for defining which team by name wins - no variable for winner by score?

**Comment by slipcor** [comment]
no, the default is "none" :) so if it is "none" it will do the calculation :)

At least that's the theory ;)

https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/loadables/ArenaGoalManager.java#L267

**Comment by mibby** [comment]
Played three games of CTF with winner: none. As team red scoring (being in the lead), it ended with it stating it was a draw, no winners. Game 2 - as team blue scoring (being in the lead), it ended with team blue winning. Game 3 - as team red scoring (being in the lead - re-testing to confim bug), it ended as a draw again.

Debug of game 2 and 3.
http://paste.ubuntu.com/16716384/

**Comment by mibby** [comment]
@slipcor https://github.com/slipcor/pvparena/commit/21dcd29a73dae5819f341de34065bc83cf413996 did not fix the problem. Same as before. Works for team blue, doesn't for team red.

**Comment by mibby** [comment]
@slipcor Bump, as it isn't 'waiting'. :P

**Comment by slipcor** [comment]
@mibby now it is though :) plz check!

**Comment by mibby** [comment]
Confirmed fixed. Tested with both team in the lead in two separate games. Team red and team blue were both able to be defined as 'winners'.
