### ISSUE TITLE
[Bug] [Module - Duel] MODULE_DUEL_NODIRECTJOIN does not work for arenas in a shortcut configuration.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#134]

**Comment by slipcor** [comment]
can you clarify "does not work" ? what happens?

**Comment by mibby** [comment]
I don't remember exactly but I think if multiple duel arenas are in a shortcut configuration, the nodirectjoin message does not output. I don't really use the nodirectjoin message so if you can't locate a logic problem in the code, feel free to just close this.
