### ISSUE TITLE
[Bug] [Module - Duel] Can request to duel someone in another arena.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#135]
You should not be able to request to duel someone if they are already part of another arena. The person could accept the duel request while in the other arena, causing it to bug out.

**Comment by slipcor** [comment]
no they could not... could they? .. OH pa commands are allowed xD

awesome sauce. yes. will fix!

**Comment by slipcor** [comment]
v1.3.2.57 - address github issue #135
