### ISSUE TITLE
[Suggestion] [Module - Tournaments] Support for arena tournament functionality.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#137]
Maybe something similar to BattleArena functionality?
http://wiki.battleplugins.org/BattleArena/Tournaments

![link](http://i.imgur.com/3azpxyp.png)

Where tournaments would be a pre-planned big event on the server to schedule ahead of time and get teams. Bigger bracket depending on number of teams or what arena goal the tournament is based around (CTF would be most popular I think.).

Would also need to lock down the arenas/shortcut rotation during the tournament to avoid people from starting it normally outside the tournament. 

And bigger payout to the winner of the tournament?

**Comment by slipcor** [comment]
yeah for a team arena setup, let's do this version, and for a FFA setup we need a bigger tree and maybe some group system like in soccer. Or restrict it to 16 ppl. I dunno :D

**Comment by mibby** [comment]
Closing ticket. I personally have no more interest in a bracketed leader-board tournament so closing to reduce the possible work burden to implement / fix. Feel free to re-open if this is something you do want to implement.

Besides, it would have to be a scheduled thing anyways due to how many players it would require.
