### ISSUE TITLE
[QUESTION] BlockDissolve : 2 blocks remove instead of 1?

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#141]
Why 2 blocks are remove when we run ? 

Is it because player walk in the middle ?

Can we configure to have only 1 block remove ?

Thanks.

**Comment by mibby** [comment]
I believe it is to prevent an edge case of one block being removed but the other not, where users in between two blocks would not fall.

**Comment by Oruss7** [comment]
Can we disable this feature ?

**Comment by slipcor** [comment]
Not atm. I could add a config setting for that but this would allow players to stand still because they are on the edge and stay on less than half of the next block, keeping them from falling oO

I did not think anyone would anticipate or want to enforce this kind of behaviour Oo

**Comment by Oruss7** [comment]
And adjust the calcul ? I run in the middle of row block but the near blocks are dissolve to.

**Comment by slipcor** [comment]
sure. good luck :)

**Comment by slipcor** [comment]
I added a config setting, grab the last builds

https://ci2.craftyn.com/job/PVP%20Arena/
https://ci2.craftyn.com/job/PVP Arena Modules/

**Comment by Oruss7** [comment]
Thx

**Comment by slipcor** [comment]
tell me if it works :D

**Comment by Oruss7** [comment]
i'm waiting me friend to upload on the server

**Comment by Oruss7** [comment]
Perfect ! Gut Arbeit (i learn deutch for 4 years but forgot now ^^)
