### ISSUE TITLE
[Question] WorldEdit module

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#142]
I have 2 regions to regen, can you wait region 1 is fully regen before load region 2 ?
Or it's worldedit and you can't do anythings ?

World edit cause lag with large battleground. Divide regions to load one by one will be a good solution.

**Comment by slipcor** [comment]
try it :) I think WE will handle it. And I'd say if you don't use the Async-Worldedit-thing it should do it one by one

**Comment by Oruss7** [comment]
is this ? 
https://www.spigotmc.org/resources/asyncworldedit.327/

**Comment by slipcor** [comment]
yeah I have no idea how this will turn out as I never used it. try it ;)

**Comment by Oruss7** [comment]
I will, thanks.
