### ISSUE TITLE
[BUG] choose class via command

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#143]
I have lobby with pressure plate and commandblock with command : `/sudo @p pa -ac Tank`. 
That's more user friendly. 

But with latest build, the **first command** is not working. We must run 2 time the command `pa -ac Tank` to have the class. 

Only the first don't work.

Thanks

**Comment by slipcor** [comment]
mhhh what does happen to the player when the command is issued first? Do they get added to the arena? messages? warnings?

**Comment by Oruss7** [comment]
No messages, no errors ...
- First : 
  - `You have switched to Pyro`
  - armor is not set. 

- Second : 
  - `You have switched to Pyro`
  - armor is set as well. 


More fun : I can fight without class if i don't press twice the pressure plate.

----------------
version : 1.3.2.59

logs:
```
[20:53:37] [Server thread/INFO]: CommandBlock at 1 003,72,-621 issued server command: /sudo test1 pa -ac Tank
[20:53:42] [Server thread/INFO]: CommandBlock at 1 001,72,-621 issued server command: /sudo test1 pa -ac Pyro
[20:53:45] [Server thread/INFO]: CommandBlock at 1 001,72,-621 issued server command: /sudo test1 pa -ac Pyro
[20:53:47] [Server thread/INFO]: CommandBlock at 1 003,72,-621 issued server command: /sudo test1 pa -ac Tank
```

arena config : 
http://pastebin.com/S0RGCgUj

**Comment by Oruss7** [comment]
And I Have the same problem with run **directly the command**

**Comment by Oruss7** [comment]
commands/PAG_ArenaClass line 114

You write :

```
if (!arena.getArenaConfig().getBoolean(CFG.GENERAL_CLASSSWITCH_AFTER_RESPAWN) || !arena.isFightInProgress()) {
            InventoryManager.clearInventory(aPlayer.get());
            if (aPlayer.getArenaClass() != null) {
                ArenaPlayer.givePlayerFightItems(arena, aPlayer.get());

                arena.msg(sender,
                        Language.parse(arena, MSG.CLASS_SELECTED, aClass.getName()));
            }
            aPlayer.setArenaClass(aClass);
        } else if (aPlayer.getArenaClass() != null) {
            arena.msg(sender,
                    Language.parse(arena, MSG.CLASS_SELECTED_RESPAWN, aClass.getName()));
            aPlayer.setNextArenaClass(aClass);
        }
```

`aPlayer.getArenaClass() != null` => the first time, you havn't class. So, you **never** `givePlayerFightItems()` the first time.

**Comment by Oruss7** [comment]
v1.3.1.14 - use the SNAPSHOT distinction and address github issue #85
