### ISSUE TITLE
[Request] Command /pa <arena> win <team/player>

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#146]
I searched but not found a command to force team/player win (run as console and Op players) 

Can you add it please ?

Thks

**Comment by Oruss7** [comment]
like redstone triggers module but runnable with commandblock and admin players

**Comment by Oruss7** [comment]
v1.3.2.91 Command not found.

**Comment by slipcor** [comment]
Oh wow, somehow git didn't push what I committed... please check build #92 - I didnt hook the command, it should work with #92 :)

**Comment by Oruss7** [comment]
using /pa forcewin <team/player>
