### ISSUE TITLE
[Bug] Region priority overriding protection flag settings.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#152]
![link](http://i.imgur.com/zuSgOt6.png)

All regions are a BATTLE region. 
All regions have the same protection flags set, with the exception of region A-D.
Region A-D are set to allow block place and break.

Players can't build in region A-D because the battlefield region is flagged to protect against place and break within its region. I'd like to be able to prioritize region A-D and allow block place/break when in those regions. To allow players to place and break, I have to flag the battlefield region with place and break false. But I don't want to allow players to build within the battlefield region!

Region priority list perhaps?

**Comment by slipcor** [comment]
this will have to happen in 1.9 - I need to rewrite how the config is written. I cannot continue adding things to the lines and hope it won't break :) I will change how regions are stored

**Comment by mibby** [comment]
Closing ticket. I personally no longer use this module so closing to reduce the possible work burden to implement / fix. Feel free to re-open if this is something you do want to implement. In most cases, arenas should only have 1 actual battlefield region. Walls was a unique situation.
