### ISSUE TITLE
[Enhancement] [2.0] 1:1 inventory saving and loading

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#153]
Properly save and load class inventories based on the exact definition it is saved in. For example, having a compass in slot 9 of your hotbar and nothing else. Current behavior purges empty slots and moves it to slot 1.

**Comment by mibby** [comment]
@slipcor Not working as intended. Not saving items 1:1. 

Had a clock in slot 2, compass in slot 9, and a shield in the off-hand. Saved the class via ```/pa <arena> class save <name>```.  Clock and compass ended up in slots 1 and 2, in that order.

**Comment by slipcor** [comment]
yes hahaha I messed up the tagging :)

Sorry for the confusion :)

**Comment by mibby** [comment]
Closing ticket. @slipcor Correct me if I'm wrong but I believe this is now done with the ItemStack list implementation.
