### ISSUE TITLE
[Bug] Class inventory drops in spectator when teleported to spectator location on death.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#155]
The class inventory items seem to drop on the ground in the spectator location when you are teleported to spectator on death. This is made apparent when the region is flagged to allow drops.

**Comment by mibby** [comment]
After further testing, it seems it drops the entire inventory you had when fighting in the arena. But the drop is a clone. The items drop in the arena AND they drop in the spectator area.

**Comment by slipcor** [comment]
@mibby I hate to be that guy, as late as I am, but do you happen to have the config for that? It seems to be a special case. I have checked obvious issues in the code but I do not see anything that could/should duplicate, so it has to be a config/module combination specific situation :/

**Comment by mibby** [comment]
Arena config.
http://paste.ubuntu.com/16719815/

Debug.
http://paste.ubuntu.com/16719849/

Screenshot from each perspective. Inventory was dropped in both areas, once where the player was killed, once where the player was brought to spectator location.

![link](http://i.imgur.com/ZQPpwsN.png)
![link2](http://i.imgur.com/cqeeDZM.png)

**Comment by mibby** [comment]
No longer drops inventory in spectator lounge, but noticed another problem. Equipped armor drops twice on death. Unequipping, it doesn't seem to duplicate.

**Comment by slipcor** [comment]
hmm sry can I get a debug on that? or actually I would love to push this to the 1.9 milestone, this clearly is an issue with the inventory being handled differently now, much similarly to MobArena, before, I handled ArmorContents and Contents seperately, where now Contents does contain ArmorContents, too.

For backwards compatibility reason this would need a lot of fixes :/

**Comment by mibby** [comment]
Normal deaths only duplicate the drop of the helmet. Final death of a player (the one that brings them to spectating location) duplicates all equipped armor on drop.

Debug.
http://paste.ubuntu.com/17080316/

**Comment by mibby** [comment]
@slipcor I believe this issue is finally fixed in either of these commits.
https://github.com/slipcor/pvparena/commit/359dc05e22f290533716cea5ddf7f14d896c072f
https://github.com/slipcor/pvparena/commit/bbd30fac814c462179b82b08a94219b44749eaa3

As I can't seem to reproduce the dupe on death / spectate teleport anymore.
