### ISSUE TITLE
[Bug] Teleport protection flag does not work.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#157]
The teleport protection flag does not currently work, testing with a BATTLE region. Tried setting the protection for teleport to true and false.

**Comment by slipcor** [comment]
wasn't this resolved?

**Comment by slipcor** [comment]
hi?

**Comment by mibby** [comment]
Going to be honest, don't remember why I created this ticket. I think it was bugged but you fixed it. Going to close in the meantime until I run into problems with the teleport flag again.
