### ISSUE TITLE
ColorTeam : remove Tag API dependance

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#165]
With bukkit 1.8, TagApi is no require. 

> A note about the future. 1.8 and beyond

> With the changes implemented in 1.8, TagAPI is no longer a good idea. As a result, TagAPI will receive no further updates.

**Comment by slipcor** [comment]
so how do I color people's names? Does it work on its own? :)

**Comment by Oruss7** [comment]
With bukkit colors. No external plugin require since 1.8.
But I havn't found examples on internet....

**Comment by Oruss7** [comment]
Apparently, just setDisplayName with bukkit chatColor work fine.

**Comment by slipcor** [comment]
please test :)

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

to be fair, I do more than just setting the displayname, I add them to a scoreboard, so this has to work, and it did work, and I have no idea why you wanted  me to remove tagapi support because it does not hurt anyone to have it in there, but I did it :P

**Comment by Oruss7** [comment]
Not working. We try to remove deprecated plugins like TagAPI, 

>A note about the future. 1.8 and beyond

>With the changes implemented in 1.8, TagAPI is no longer a good idea. As a result, TagAPI will receive no further updates.

see [tagAPI-bukkit](http://dev.bukkit.org/bukkit-plugins/tag/)

**Comment by slipcor** [comment]
well if it is not working now but it worked before then clearly removing it was a bad idea -.-

so, what do we do now? do I send everyone who had this working with TagAPI to you?

**Comment by Oruss7** [comment]
Can you wait, i search example of working plugin with Bukkit chat color name.

**Comment by slipcor** [comment]
OH sure, I can not do anything BUT wait, I am at work right now xD and well I did not publish the fixes yet so I assume it might not have broken too many servers

**Comment by slipcor** [comment]
I have tried looking for an alternative, it seems that it is not possible. Every plugin doing this uses NMS hacks and I will not do those. :P

**Comment by Oruss7** [comment]
I see this week-end. I keep you informed

**Comment by slipcor** [comment]
well the weekend is over :P can you try the latest modules, 74? I think I might have found a logic error on my end :)

If it does not work please be more precise about what you're trying to do, and maybe pastebin your config?

**Comment by Oruss7** [comment]
http://pastebin.com/6NHATU2z

Don't have color on head and don't have scoreboard :sob:

**Comment by slipcor** [comment]
@Oruss7 which module version are you using? - it should be v1.3.2.94

**Comment by Oruss7** [comment]
Working fine. Thanks !
