### ISSUE TITLE
[Enhancement] Support off-hand slot for inventory & class chests.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#171]

**Comment by slipcor** [comment]
@mibby I think I have fixed this in the first 2 builds. It should be the 5th to last thing in a class, and saving and loading via command should work since 1.3.3.* !

**Comment by mibby** [comment]
Not sure what you mean by saving and loading via command. As in saving class inventory when wearing an item in your offhand properly adds the value in the class config section now (outside of using class chests)?

In any case, offhand slot is a bit buggy when switching classes. 

Video showing problem.
https://www.dropbox.com/s/tke0ift0utxb4fy/2016-07-06%2005-12-29.mkv?dl=0

Debug.
http://paste.ubuntu.com/18629962/

Class switching is fine when there is no offhand slot in use. I tested this with a classchest. Assuming behavior would be the same with a class loadout in the config (no class chest), with an offhand item defined.

**Comment by slipcor** [comment]
I will look into the debug, but loading from chest is different type of loading than from config. I.e. config can be more buggy, however I will have to look at the video when I am home, and I only can imagine it being there or not there - if we are unlucky, it does not show THAT it is there.... but well, I will check this

**Comment by mibby** [comment]
Ignore former statement. Seemed to have been caused by a conflicting plugin that modified combat. Switching classes with items in the offhand slot (5th from last row - class chest) functions fine. Thanks. :)
