### ISSUE TITLE
Suggestion: Make Blockrestore Module restore Lava & Water 

### ISSUE THREAD

**Issue by BerndiVader** [slipcor/pvparena#176]
Hi! First to say its a great Plugin thx alot for it! I have a little suggestion: Is it possible to add the PlayerBucketEmptyEvent to the Blockrestore Module. For now lava & water placed with Bucket will not be restored. Thx alot.

**Comment by slipcor** [comment]
Did you test that? At least back in the day (when I created the module) this event also caused a "place" event that would be restored :)

If you verified that it does not, I will try hackfixing this :/

**Comment by BerndiVader** [comment]
Hi! When the Water/Lava is floats the last stage isnt restored but replaced with a stationary block. But now i understand why there was stationary water and lava blocks instead.

Not very much that i can do in java but this changes work

https://github.com/BerndiVader/pvparena_modules/commit/29146f64e9247cb951ccd6c08ca76f0b1f402775

https://github.com/BerndiVader/pvparena_modules/commit/847ecbebcbab40c7f784700a01a37a5376040d58

**Comment by slipcor** [comment]
hmmmm but this only resets PLACING of lava and water - before it would also undo the REMOVAL of liquids. I will check this tomorrow and probably fix it then .I hope this was not just a 1.9 addition, I am trying to keep PA 1.8 compatible ;)

**Comment by slipcor** [comment]
@BerndiVader thanks for your code, I decided to attempt it a little bit differently. If this does not fix it, I will do it your way!

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/88/artifact/dist/target/files.zip

Can you check this blockrestore if v1.3.2.105 works as intended?

**Comment by BerndiVader** [comment]
@slipcor hI! thx for your changes. it restores now all the floating blocks but the stationary blocks still remain. the stationary blocks on the pic are the ones where i placed water/lava with bucket. dunno your code but me think what left is to catch the emptybucket event to get the lava that is placed. but me sure you know already :D thx alot!


![2016-05-04_21 44 56](https://cloud.githubusercontent.com/assets/18723791/15027063/f522f520-1241-11e6-982e-177c6369968f.png)

**Comment by slipcor** [comment]
Okay, I will do what you did xD But please do me a favor, and check whether it re-places stuff you REMOVED during a match, ok?

Please try the download link again, it should be at version #106 and is theoretically identical to your version of fixing it (and added BukketFillEvent)

However, your way of doing the ArenaBlock.restore() strikes me as only ever replacing it TO AIR, so it never might re-place lava/water you removed :/

**Comment by BerndiVader** [comment]
@slipcor hi! just tried it out. still, it refuse to replace the lava placed with bucket. the screenshot where u can see the stationary blocks is with your ver the one without stationary blocks is with the  hack. the emptybucket part did the job catching stationary water/lava. the mean part in the arenablocks, that one with the air, get the floating blocks. but it looks like you got a good way to get the floating ones. maybe combo both. :D 

![2016-05-04_23 33 57](https://cloud.githubusercontent.com/assets/18723791/15030307/da90e8ce-1251-11e6-8ea2-911f6522ed9f.png)
![2016-05-04_23 40 43](https://cloud.githubusercontent.com/assets/18723791/15030308/da94d1a0-1251-11e6-9ffc-181a8a9e1d1c.png)

**Comment by BerndiVader** [comment]
ps: it dont replace blocks others than water/lava. i tried it with a chest and it wont replace it with air. so i destoryed the chest placed water instead of the cheat during a fight. the chest will restore and so will do the other blocks. BUT it will not replace water / lava. thats the air part in arenablocks that caused that.

**Comment by BerndiVader** [comment]
hi! sry the file you linked above pointed to an old version, my fault i should have checked the ver... #106 works. #105 didnt work. thank you.
