### ISSUE TITLE
Betterfight one-hit kills

### ISSUE THREAD

**Issue by wazoomie** [slipcor/pvparena#177]
The one-hit kill functionality doesn't work with Snowballs, and probably all other projectiles.

This error is thrown:
`Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Projectile.getShooter()Lorg/bukkit/entity/LivingEntity; at net.slipcor.pvparena.modules.betterfight.BetterFight.handle(BetterFight.java:200) ~[?:?]`

**Comment by slipcor** [comment]
Please update the modules :) you are using a 1.7 version of a module ;)

https://www.spigotmc.org/resources/pvp-arena.16584/history

Here are the downloads, so the latest plugin is top, the latest files download is the second :)

**Comment by wazoomie** [comment]
Thanks for the quick response! I couldn't find the new files so I thought I was up to date. Downloading the latest files fixed the issue(s) for me. Thanks again.
