### ISSUE TITLE
Cancel enderpearl Teleportation on death

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#178]
Hi, can you cancel enderpearl teleportation on death plz ?

When we throw an enderpearl and die, we are teleported after respawn. And when go ta spectate area, it's the same.

Thanks

**Comment by slipcor** [comment]
wow that's a catch right there xD I'll try to :)

**Comment by Oruss7** [comment]
pa 1.3.2.119 => not resolved

**Comment by slipcor** [comment]
@mibby can we debug this some day? I thought I fixed it :/

**Comment by Oruss7** [comment]
After read your code, I think, you don't understand my problem.


Players throw enderpearl. Some throw many on the void. They fall and die.

After respawn, enderpearl previously throwed fall on the floor and players die instantly because when player die, enderpearls are not desactived and continue to fly.

**Comment by Oruss7** [comment]
Maybe can i add 10 seconds before player respawn. During this time, enderpearl teleports are cancelled

**Comment by slipcor** [comment]
Well what did you think I was trying to do then? When you die, you are not alive or you are already out of the arena, not playing. So in either case THEN you should nnot be teleported by an enderpearl.

But this is exactly what is happening even thogh I tried to fix that oO

Exactly what you described what was I understood what is happening and should no longer be happening after I did the commit ;)

**Comment by Oruss7** [comment]
but when player respawn (he have 10 lives), he is teleported anyway because before die, he have launch an enderpearl on the sky

**Comment by slipcor** [comment]
oh you mean on respawn like, INSIDE of the game because of "you have lives left" - well that is a different thing xD

Hmm the only thing you could fix this is with "Respawnrelay" this puts players into a state where they are "dead" (and cannot teleport, obviously) sooo that should fix it!

https://github.com/slipcor/pvparena/blob/master/doc/mods/respawnrelay.md

**Comment by Oruss7** [comment]
Done with Respawnrelay module. Thanks you
