### ISSUE TITLE
Spectate

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#179]
Using Mod pa_m_spectate.jar, command = /pa Areaname spectate. response of pvparena is: "Error! No player found!"

**Comment by slipcor** [comment]
yeah this is supposed to happen when there is no player playing yet but someone tries to spectate. Essentially, the module is hooking spectators to a player, but there s noone to hook to :)

Right?

**Comment by CCCCarsten** [comment]
Yezzz! :) I am expecting the possibility to spectate "out of pvp", only watch a fight. Why should I join "Team red" and then spectate? ;))

**Comment by slipcor** [comment]
No :) just use "flyspectate" for example. the "spectate" is strictly tied to a palyer, so without someone WHO IS PLAYING there is no possibility you can spectate anyone :)

With flyspectate though, you can join BEFORE the match and fly around ;)

Maybe German? :P

**Comment by CCCCarsten** [comment]
Okay... :)) ....flyspectate erzeugte bei mir Errors (in der alten Version). Ich probiere es - jetzt nach dem Update - noch einmal. Richte Dich auf das schlimmste ein... :P

**Comment by slipcor** [comment]
www.pastebin.com ;)

**Comment by CCCCarsten** [comment]
pastebin ist noch nicht dran :O). Nachdem ich vorher "spectate" deinstalliert habe:
/pa install flyspectate
/pa STADION !tm flyspectate
Vorsichtshalber Server-Neustart :)
/pa STADION spectate
Und jetzt die Überraschung :P :P : :P 
.
.
.
.
.
.
error: No player found!                         (Ein Teufelskreis ;))))

**Comment by slipcor** [comment]
@CCCCarsten 

Hmmm ich hab dann mal was erlaubt, ich hoffe es macht nix kaputt:

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/dist/target/files.zip

version v1.3.2.105 vom FlySpectate sollte klappen!

**Comment by CCCCarsten** [comment]
Moin SLiPCoR,

das FlySpectate aus dem obigen Link setze ich bereits ein. (siehe auch PM --> SPIGOT). Die Time Stamps und die CRCs von "meinem" bereits eingesetzten FlySpectate sind jedenfalls alle identisch, wenn ich in das JAR-File hineingucke. Gib's zu: Du wolltest nur ausschließen, dass ich die falsche Version habe und zu doof dafür bin xD xD xD....... :)))

**Comment by slipcor** [comment]
Nein, die Sachen gehen ja parallel und ich verliere schon mal den überblick. Wichtiger als Timestamp und CRC sind /pa version :D steht dann da FlySpectate: 1.3.2.105? oder inzwischen sogar 106 :)

**Comment by CCCCarsten** [comment]
Ufffffff........ 1.3.2.103 ....... a propos Überblick ;)) : Wo liegt denn die neueste Version gerade herum? Ich poste Dir mal /pa plugin als PM in Spigot...

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/dist/target/files.zip

der link ist immer gültig. MIST Ich hab jetzt die ZIP Datei aktualisiert. Die Automation da klappt noch nicht wirklich :(

**Comment by CCCCarsten** [comment]
Using Mod FlySpectate. Users can not fly. Have I to remove "StandardSpectate" in areaname.yml?

"/pa AREANAME spectate" klappt jetzt :). Die WATCH-Zone und die BATTLE-Zone hatten sich überschnitten :((((( . Fliegen können die "spectators" allerdings nach derzeitigen Erkenntnissen nicht (MOD FlySpectate). Muss im Areaname.yml "StandardSpectate" vielleicht entfernt werden?

**Comment by slipcor** [comment]
versuchs mal

**Comment by CCCCarsten** [comment]
Flug ist jetzt möglich ;), allerdings nur, wenn das Spectate-Kommando von derselben Welt initiiert wird, auf der sich auch die PvP-Arena befindet. Vermutlich wird ansonsten der Creative-Modus des Spectators von Multiverse Core (Multiworld-System) überschrieben. Ich glaube, dass dies damit erledigt ist. :O)

**Comment by Oruss7** [comment]
Can you translate in english please ? What solve this issue ?

**Comment by CCCCarsten** [comment]
Hi Oruss7,
sorry for non-english ;).
I have deleted the "StandardSpectate" in the areaname.yml. Furthermore I have found out that the spectator turns up to creative modus = fly only then if he starts at the same world as the arena is.
Ciao, Carsten

**Comment by slipcor** [comment]
Yeah it is almost impossible to fix it for every world plugin, @Oruss7 

If you have a similar issue about flying not working or people flying, and your arena is in a creative world, this bug might be happening for you, too.

I did my very best to try to fix things. I added delay, I saved gamemodes and try to enforce it the best I could, but still ... it somehow breaks :/

You can "fix" this by only allowing joining from that world, by setting the "join.range" to 1000000 or any other number as high as your world border length ;)

Then people only can join/spectate from that world :)

**Comment by Oruss7** [comment]
Okay, so don't put arena on creative worlds. 

On my server, i always put command blocks so players don't know PA commands and don't join an arena without walk on pressure plate or push button =D

That's can be usefull for your situation @CCCCarsten

**Comment by CCCCarsten** [comment]
Hi @Oruss7 ,

yes, I am using command blocks since I can think ;)). Thanks!
For the spectator modus it is necessary to start spectating on this world as the arena is.
The spectator turns up to creative modus and this is why he can fly. Mod "flyspectate".
