### ISSUE TITLE
install.yml

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#180]
The install.yml does not contain the complete components, for example "spectate" and "titles".

**Comment by slipcor** [comment]
ugh thanks, I will update it xD

**Comment by Oruss7** [comment]
Yes i confirm titles is not in install.yml ^^

**Comment by slipcor** [comment]
I knooooooow :P I'm on it xD

**Comment by slipcor** [comment]
should be fixed on next restart :)
