### ISSUE TITLE
Bug about Playerdamage

### ISSUE THREAD

**Issue by BerndiVader** [slipcor/pvparena#181]
Hi! I found a bug that belongs to the Playerdamage: If we pvp in an arena (no matter what goal or mod) it happens that after some random time we receive damage like crazy. The attacker can damage the victim much faster. Also Lava or Fire Dmg is much faster. Like there is almost no Dmgdelay.

This effect is active the whole time the player is in arena, no matter how much he died there. The effect stay active after the arenafight and the player is back in world. But if the player dies in the World without pvparena the effect is gone. Logging out also quits this effect. I know this is very hard to find as it seems to appear random. 

I used only pvparena as plugin without any other mods. Version is 1.3.2.105 running on Spigot 1.8.8

First thought was that the player duplicate in Arenaplayerlist but the effect remain then outside of the arena.... Dunno very strange. And me sure i am the only one because there is no other ticket for this .D

And sry for me english. really. And thx for this great plugin.

**Comment by BerndiVader** [comment]
Hi! I was tracing for the bug myself. Tracked the players damageticks MaximumNoDamageTicks, NoDamageTicks they are not the issue. Also the player is not in any arenalist neighter. So i downgraded to Spigot-db6de12-07c3001 and the issue was gone..... will check if 1.9 is affected tooo

**Comment by slipcor** [comment]
wow what oO this sounds crazy :O

What damage delay are you talking about? 1.9 has changed a lot of things so it will be different, I am not really understanding what you mean. Maybe the TICKS increase? (lava kills you quicker because it ticks quicker?)

I would not even know how to change those settings so I can only say that I cannot see where and how I would have done that :O

**Comment by CCCCarsten** [comment]
I agree with BerndiVader. I think (I don't really know ;)) it is similar to my problem. After leaving the pvp-Arena the players are not completely "reset". In my case the player gets back his gamemode "creative", but can't fly. "Log out" and "Log in"  would be the solution - or changing the gamemode to x and then back to creative.

**Comment by BerndiVader** [comment]
Setting the resetDelay in the arena.yml to 1 did if for me. thx.

**Comment by slipcor** [comment]
@CCCCarsten does that fix it for you too maybe? Thanks for trying that and sharing it, @BerndiVader !

**Comment by CCCCarsten** [comment]
Unfortunately not. User are definitely in creative modus and can not fly (after exit the arena).

**Comment by slipcor** [comment]
okay let's check this in your ticket then :) closing this!
