### ISSUE TITLE
DiscordMC and Fight Messages

### ISSUE THREAD

**Issue by wazoomie** [slipcor/pvparena#182]
I'm using [DiscordMC](https://www.spigotmc.org/resources/discordmc.17067/) to display messages from Minecraft on Discord and vice versa. The messages seen during a pvp arena match show up on Discord, even though they're only supposed to be shown to participants ... and they show up as _null_.

http://puu.sh/oE5dj/cbdcb9eff0.png

The messages are listed in _lang_en.yml_ under _nulang.fight_.

Is this something you could possibly fix or is this something the developer of DiscordMC should take a look at?

**Comment by slipcor** [comment]
Try asking the DiscordMC dev first, what this "null" can be and how you can find out WHY it is null. I never send "null" , max / min I send is an empty string, and that normally does not send anything, at all.

You can try to remove your lang file though (so it replaces it with a default one), if this works, you somehow messed up your old language file :P
