### ISSUE TITLE
[FEATURE REQUEST] "Checkpoint" system - teleport to defined checkpoints in an arena after reaching them

### ISSUE THREAD

**Issue by tmad40blue** [slipcor/pvparena#184]
Hey slipcor, we talked about this on IRC briefly, but I'd love to see a "checkpoint" system in PVPArena. It could work like this:

- Arena owner sets the "checkpoint", either as a region, spawn, clickable sign/item, or a combination of these

- When a player reaches the checkpoint during the fight, it is "saved" that the player now has access to reach said checkpoint (either for only that round, or perpetually)

- Player can now teleport to that checkpoint at any time during the round, either by typing a command (i.e. /pa <arena> checkpoint <1, 2, ... n>) or by clicking a sign or other item (i.e. a sign with "Checkpoint" on line 1, and the checkpoint name/number on line 2)

This would make it way easier to create parkour, and other big arena maps, with PVPArena.

Thanks!

**Comment by slipcor** [comment]
@tmad40blue good luck with https://github.com/slipcor/pvparena/blob/master/doc/goals/checkpoints.md

**Comment by tmad40blue** [comment]
After a few builds, CheckPoints seems to be working great 100% of the time, so I'll close this issue now.
