### ISSUE TITLE
[BUG ?] Module Worldedit

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#185]
`/pa [arena] !we region - toggle specific region loading/saving (using this command creates a list of arena regions that will be saved/loaded)`

This command create a new region instead of toggle specific region loading/saving. 

Or i don't understand this command ^^'

**Comment by Oruss7** [comment]
And please accept https://github.com/slipcor/pvparena_modules/pull/15 ^^

**Comment by slipcor** [comment]
done, pulled and should be on the latest jenkins!

**Comment by Oruss7** [comment]
and for the `/pa [arena] !we region`, is it normal ?

**Comment by Oruss7** [comment]
I forgot to up version on install.yml

**Comment by slipcor** [comment]
Actually the documentation and game errors messages were wrong :D there is no toggle when you don't specify whether to load or to save ;)

So yes, it is normal :)

**Comment by Oruss7** [comment]
Ok, thanks. An other thing :  
regions node is for say which regions we use worldedit right ?
![capture](https://cloud.githubusercontent.com/assets/4788317/15292060/791c6a26-1b81-11e6-9997-9264a4cd11da.PNG)
But it continue to load/save ALL regions on this arena ='(

**Comment by slipcor** [comment]
please make sure you are on latest version. check the code here, it is ... clear imo:

https://github.com/slipcor/pvparena_modules/blob/master/m_WorldEdit/src/net/slipcor/pvparena/modules/worldedit/PAWE.java#L276

the path to that node is "modules.worldedit.regions" ?

**Comment by Oruss7** [comment]
Ah yes that's code is clear. I will check the YAML and PA version...

**Comment by Oruss7** [comment]
```
for (final ArenaRegion ars : arena.getRegionsByType(RegionType.BATTLE)) {
                save(ars);
            }
```
save all regions with BATTLE type ?

**Comment by slipcor** [comment]
But look where I linked, that is exactly what I do.

when regions contains more than NOTHING - I only do _those_ and then RETURN (exit)

The code you linked (do all) only is executed if there are no regions set specifically

**Comment by Oruss7** [comment]
Oh don't see the return. My bad.
