### ISSUE TITLE
BetterClasses URL include no link

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#187]
https://github.com/slipcor/pvparena/blob/master/doc/mods/betterclasses.md

At the bottom... "Potion Effect Types" --> "click me" <-- No link

Ich sach nur "INCREASE_DAMAGE"-Ratespiel ;))))

**Comment by Oruss7** [comment]
Sorry i fix as soon as possible

**Comment by slipcor** [comment]
@Oruss7 I did it :)
