### ISSUE TITLE
(1.9+) Support enabling/disabling player collision in scoreboard.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#188]
In MC 1.9+, there is a setting to set collision state.

http://minecraft.gamepedia.com/Scoreboard
scoreboard teams option <team> collisionRule <always|never|pushOwnTeam|pushOtherTeams>

A toggle to enable/disable collision while in the arena would be great to have. :)

**Comment by mibby** [comment]
Set ```collision: false``` and reloaded the arena. Collision is still present in the lounge and in-game battlefield. Ideal behavior is to disable collision when part of the arena and restore previous state on leave.

http://paste.ubuntu.com/18629060/

**Comment by mibby** [comment]
Still not working as intended. 

```
collision: false
```

Collision is still enabled in lounge and battlefield.

Debug.
http://paste.ubuntu.com/18676688/

**Comment by slipcor** [comment]
@mibby has to work now

**Comment by slipcor** [comment]
oh you do realize that this also includes arrow collision?
