### ISSUE TITLE
Nice to connect with LeaderHeads :)

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#193]
Hi SLiPCoR,

would be nice if you connect with [https://www.spigotmc.org/resources/leaderheads.2079/]. It is a nice plugin to make fantastic stats :). 

Ciao, Carsten

**Comment by slipcor** [comment]
well at least they offer API download. I will look into it, probably will add a module for that ;)

**Comment by CCCCarsten** [comment]
Thanks, danke, merci, gracias, grazie! :)) Nimm das Modul am besten gleich für eine Premium-Version. Ich finde immer noch, dass Du darauf hin arbeiten solltest. :))

Use this new modul for a premium version. I think your plugin should turn up to it.

**Comment by RobiRami** [comment]
If help is required, contact me.

**Comment by slipcor** [comment]
thanks so much! I have been busy with some internal changings and updating to 1.9 :) I will start working on this soon and appreciate the help offer :)

**Comment by slipcor** [comment]
Well the API is to read values, but Carsten wants the plugin to read from my information, sooo I think @RobiRami this is for you then :)

https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/managers/StatisticsManager.java

here a snippet:

`Arena arena = ArenaManager.getArenaByName("myArena");
StatisticsManager.type type = StatisticsManager.type.getByString("KILLS");
ArenaPlayer[] players = StatisticsManager.getStats(arena, type); // returns an Array of players, ordered by the type, descending!
String playerName = players[0].getName(); // player can be offline - you can try to get with with:
Player onlinePlayer = players[0].get(); // but it can be null of offline ;)
String nice = type.getNiceName(); // "Kills" - configurable in the language file`

Currently those are the statistics we have:

`WINS("matches won", "Wins"),
LOSSES("matches lost", "Losses"),
KILLS("kills", "Kills"),
DEATHS("deaths", "Deaths"),
MAXDAMAGE("max damage dealt", "MaxDmg"),
MAXDAMAGETAKE("max damage taken", "MaxDmgTaken"),
DAMAGE("full damage dealt", "Damage"),
DAMAGETAKE("full damage taken", "DamageTagen"),
NULL("player name", "Player");`

**Comment by slipcor** [comment]
Man I have no clue why this formatting does not work, but the line breaks should be working when you copy it -.-

**Comment by RobiRami** [comment]
Put this three backticks above and under your code:

```
like this
```

**Comment by RobiRami** [comment]
So if I'm correct, all statistics are specific per Arena or are the players just indexed per Arena ?

**Comment by slipcor** [comment]
yes, it is saved per arena. Oh I just found that you can pass arena as null, it then gets all arenas :)

**Comment by slipcor** [comment]
Just as a side note, I JUST fixed the Stats manager, since I moved to UUID I broke the stats, they reset on server start and noone noticed :P Latest release version on Spigot fixes this ;) version v1.3.3.193

**Comment by RobiRami** [comment]
Would you recommend making global leaderboards or per arena ?

**Comment by slipcor** [comment]
if possible, I would do both, to allow the server owner to choose which he wants. Like, maybe they have only one or two, then it does not matter, but maybe they want to have one display for each arena? :)

**Comment by RobiRami** [comment]
How long are these arena names ?
The problem is that I only have 16 characters to fit my leaderboard name. The name would look something like this: ps-arenaname-kills

**Comment by slipcor** [comment]
No restriction on my end. People can rename their arenas by renaming the arena file :) so if they have longer names and want to use the plugin they will find ways. 
Most names I have seen are short: ctf, free, hg, spleef; easy to type ;) 
However, the server owner decides this.

**Comment by CCCCarsten** [comment]
Oh oh oh..... I am not afraid to rename my Arenas.... no Chance. Perhaps there is the possibility to take over the first (!) 16 characters?

**Comment by RobiRami** [comment]
Yeah, that was also an idea I have. I'll have to check to see if the current code supports that.

**Comment by slipcor** [comment]
Yes, using this method should work:

https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/managers/ArenaManager.java#L161

It gets arenas with that exact name, starting with that name and ending with that name :) (first catch ;) )

**Comment by CCCCarsten** [comment]
Hi slipcor and RobiRami, what is going on? :) Ciao, Carsten

**Comment by CCCCarsten** [comment]
![bose und zetern](https://cloud.githubusercontent.com/assets/18105655/20037732/87aa4fa8-a426-11e6-9710-c55cbb49da29.gif)

**Comment by RobiRami** [comment]
Working on it.

**Comment by slipcor** [comment]
Thanks so much, I heard there was an update!
