### ISSUE TITLE
PlayerFinder

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#195]
No reaction by left or right click with compass.
Areaname.yml includes the entries.

**Comment by CCCCarsten** [comment]
Is this caused by the PlayerFinder?
http://pastebin.com/aAJTurqi

**Comment by slipcor** [comment]
yes, give me a minute

**Comment by slipcor** [comment]
v1.3.2.118 - [ArenaMaps] fix a startup error due to broken Map linking that breaks everything

**Comment by CCCCarsten** [comment]
Compass runs...! :)
