### ISSUE TITLE
SpecialJoin

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#196]
http://pastebin.com/Uhay1Ca9

**Comment by slipcor** [comment]
fixed! v1.3.2.119 - [SpecialJoin] fix plugin loading, broken on March 24th - sorry!

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

**Comment by CCCCarsten** [comment]
Great work! It is not necessary to say "Sorry". :) I will test it tomorrow.

**Comment by CCCCarsten** [comment]
installation successful! :) Anywhere, setting a join sign seems to be complicated ;)) (no success for me!) oder does not function. I have tried all kinds of possibilities. **One** try for you now :) (Spigot 1.8.8,)

Installation erfolgreich. Gut! Aber das Setzen eines "join signs" Schildes klappert nicht. Die Doku habe ich natürlich :P beachtet:
/pa [arena] setjoin - then hit what should become a join trigger.
JOIN SIGN
1: ignored 2: [teamname] #if not valid: random 3: #needs to be blank 4: ignored
Ich schenke Dir Deinen eigenen Versuch! :P
Wenn der klappt, liegt es an mir.... ;) (und an Deiner Doku :D :D :dancer: )

**Comment by slipcor** [comment]
It is on you. I just tested it on my test server. How exactly does the sign look like you try to use?

And did you activate the module for the arena???? /pa [arena] !tm specialjoin

----


Es wird an dir liegen :) Ich habs grad mal eben getestet. Nichtmal mit meiner doku sondern mit deinem zutat :) Wie sieht dein Schild denn aus?

Und hast du das Modul auch aktiviert in der arena??? /pa [arena] !tm specialjoin

**Comment by CCCCarsten** [comment]
SpecialJoin didn't function in my case because I have set line 1 of the join sign with color codes ('essentials'). If I don't use color codes SpecialJoin runs ;) 
![bose und zetern](https://cloud.githubusercontent.com/assets/18105655/15483277/349bd7a2-2134-11e6-8a08-7f6c52dbdff7.gif)


Selbstverständlich habe ich das Modul aktiviert :). Lösung: Weil in Deiner Doku steht, dass Line 1 des Schildes ignoriert wird, habe ich dort einen Farbcode eingesetzt ('essentials'). In Line 2 habe ich den Teamnamen natürlich OHNE Farbcode eingetragen. Letztendlich war es die farbige Line 1, die verhindert hat, dass SpecialJoin funktionierte. (grummel ;))

**Comment by slipcor** [comment]
whaaaaaat this should not be an issue though Oo does the color maybe transpire through all lines because of essentials?

moment das sollte aber nicht passieren !!! Oder sorgt Essentials dafür dass die Farben in allen Linien sind??

**Comment by CCCCarsten** [comment]
No, essentials set the color per line. :) Good luck by finding the problem :)))

Neeeeiiin :)), essentials setzt **pro** Zeile die Farbe. Allerdings betrachte ich das nicht technisch, sondern nur im Ergebnis. Für mich gilt also: Ich kann mit essentials pro Zeile eine Farbe setzen. Hinsichtlich SpecialJoin ist das Ergebnis reproduzierbar! Hähä xD, damit gebe ich die Runde an Dich zurück.... :P

**Comment by slipcor** [comment]
done, the problem is essentials :P I need a colorless line ;)

ja wie erwartet. Da essentials alles umfärbt ist der Inhalt nicht mehr "blau" sondern "§4blau" und so ein Team gibt es nicht :P

Es muss ne Möglichkeit geben dass das nur eine Zeile färbt und nicht alles -.-

**Comment by CCCCarsten** [comment]
Heeeeeeeeeee........... warum "closed"? :))
Essentials färbt ja nur pro Line ein. 

Beispiel "Join-Sign":

line 1 - &4Hier klicken:
line 2 - BLUE
line 3 - [leer]
line 4 - [leer]

Es ist jetzt nur Line 1 farbig.
Line 2 ist "Standard" = schwarz (BLUE ist der Teamname).

**Comment by CCCCarsten** [comment]
Nachsetzer ;)): Das obige Beispiel eines "Join-Signs" funktioniert mit SpecialJoin **nicht** !!

**Comment by slipcor** [comment]
Nooooooo 
Nööööööö
-. -

**Comment by slipcor** [comment]
Kannst du mal versuchen:

1) leer
2) BLUE
3) leer
4) &4Hier klicken

**Comment by CCCCarsten** [comment]
:)) That would now also been my proposal :). However, with the difference to move the team name in line 1. The way pointed out by you will overwrite the line 4, which indicates the number of players. But it works, of course! :)

Hehehe.... das klappert natürlich. Das wäre jetzt auch mein Vorschlag gewesen :). Allerdings mit dem Unterschied, den Teamnamen in Zeile1 zu verlegen. Die von Dir aufgezeigte Möglichkeit überschreibt natürlich die Zeile 4, die die Anzahl der Spieler anzeigt (ich bin also nicht ganz sicher, ob das klappt - aber logisch wäre es. Es ist nur ein Vorschlag - wichtig ist es nicht unbedingt. Das wäre für die Zukunft vielleicht mal eine Idee.... Keep cool - ich finde noch andere Mods :P :P :P

**Comment by slipcor** [comment]
hmm ich wollte damit nur testen ob... es an der ersten zeile allein liegt. und ganz ehrlich... ich sehe nicht warum. Mein Code ignoriert die erste zeile. Nichts dort kann ... verhindern dass ... das Klicken nicht durchkommt ... egal. ich weiss nich was man da machen kann Oo
