### ISSUE TITLE
[Enhancement] [Goal - King of the Hill / Domination] Add a visual representation of the capture radius.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#198]
Such as via rotating particle around radius size or any other possible (better) visual representation, so players know if they are in or outside the capture zone.

**Comment by slipcor** [comment]
Let's hope this does not kill the test server. It worked locally :)

**Comment by mibby** [comment]
Can you extend support to the Beacons goal? I use that instead of domination for a rotating claim zone. Don't have a domination arena setup for testing.

**Comment by slipcor** [comment]
boooo (yes)
