### ISSUE TITLE
Mod Titles

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#199]
There is (perhaps caused by update?) an "automatical" deinstallation of "Titles"...
http://pastebin.com/FHxSw9ev

Das hatten wir schon einmal... ;)) (siehe Spigot-PMs)

**Comment by CCCCarsten** [comment]
I have renewed "Titles". Success with "/pa install Titles" then... (Jar-File is in the folder 'mods' now). 
But with "/pa [arenaname] !tm [modname]" I get the error "Modul not found!".

**Comment by slipcor** [comment]
does **/pa version** show Titles? Is it version "v1.3.2.97" ? If no, update :P

**Comment by CCCCarsten** [comment]
I have the newest "titles" downloaded on Jenkins page yesterday. /pa install titles is always successful. Anywhere, /pa version does not show "Titles". But, please look at the original error.... why it has been deinstalled automatically?

Ich habe gestern bei Jenkins TITLES wegen des Fehlers extra neu gedownloadet. Die Installation ist auch immer erfolgreich (so eine Meldung wie "Ist bereits installiert" erscheint da nicht ;)). /pa version ist hinsichtlich Titles nicht erfolgreich: Wird nicht angezeigt. Es ist ja auch seltsam, dass es "automatisch" herausgenommen wurde (siehe ganz oben). Ehrlich gesagt, steige ich bei den Mods  auch nicht mehr durch.... mit /pa version werden Mods angezeigt, die ich nie installiert habe. Und Titles wird wiederum nicht angezeigt. Der Download bei Jenkins ist ein Staatsakt... ich muss die Files jedes Mal neu suchen :). Aber wie gesagt: bei TITLES habe ich nun gar keine Chance mehr. Das letzte Mal (siehe PMs SPIGOT) konnte ich es ja noch erfolgreich reparieren. Da ist irgendwo ein ganz kardinales ;) Problem.... (neeeeeeeeeeeinnn, NICHT Fehler 70!!!! ;))))

**Comment by slipcor** [comment]
aaaaaaaaaahhhhhhhhh das Modul "TempPerms" hat sich irgendwie in die titles jar reingepackt. Sauerei.

Oups, TempPerms got put into the titles jar xD

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/dist/target/files.zip

**Comment by CCCCarsten** [comment]
Hahahahaha.......... :)))))))))))))))))))))) "irgendwie", ja????? :)))))) Stimmt, und /pa version hatte mir die TempPerms auch angezeigt... sehr zu meiner Verwunderung. Jetzt wird wieder "Titles" angezeigt (Version 1.3.2.97). Die Einbindung in die Areaname.yml ist nun auch wieder erfolgreich :)

/pa version shows the correct version now. "Titles" is set to true in the areaname.yml now. Solved! :)

Wenn das nochmal vorkommt, richte ich einen Dauerauftrag bei den "issues" ein :P :P
