### ISSUE TITLE
'Error: No teams playing!' when reloading an arena while players are in the battlefield.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#202]
Reloading an arena while players are in-game, in the battlefield, outputs this 'error' in console.
```[13:03:57 INFO]: [CTF] Error: No teams playing!```

http://paste.ubuntu.com/16716747/

This does not occur when reloading an arena while players are in the lounges. Only when they are actually in battle on the battlefield.

**Comment by slipcor** [comment]
this has been pushed to the "gamemodes" jenkins, too, as all goals were affected ;)

**Comment by mibby** [comment]
Confirmed fixed.
