### ISSUE TITLE
Arena shortcut name joining issues.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#205]
```
use_shortcuts: true
only_shortcuts: true
shortcut_shuffle: true
allow_ungrouped: true
shortcuts:
  Spleef:
  - Spleef
  - Spleef2
  - Spleef3
```

If any arena is disabled in the shortcut list, players can't join via the shortname name with a case-insensitive name definition. For example, Spleef 1 and 3 are disabled. A non-opped, non 'PA duty' player tries to join with the command ```/pa spleef```. It outputs 'Arena does not exist: spleef'. 

When a player types ```/pa sple```, it outputs 'Error: Arena disabled, please try again later!'. As if it was trying to force the player to join the first arena in rotation that is disabled, even though it should move on to the next arena in rotation that is enabled.

When an opped player with 'PA duty' tries to join via ```/pa sple``` with duty mode disabled, it puts them in the first map in rotation that is disabled. Even though they aren't on duty and should join via the shortcut rotation like any other player.

When an opped player with 'PA duty' tries to join via ```/pa spleef``` with duty mode disabled, it is the same as a normal player. States the arena does not exist.

When all arenas in the rotation are enabled, players are able to join the arena with all lowercase and  closest name relation just fine.

**Comment by slipcor** [comment]
oh wow why do you have an arena called the same as the shortcut? :O

**Comment by mibby** [comment]
Why not? :P It is the first arena map of that gamemode. Seems a bit odd to name it Spleef1. Shouldn't cause any problems if the shortcut name is overriding all 'join by' names and just simply adding the specified configs to the shortcut rotation.

**Comment by mibby** [comment]
@slipcor I can now join with the name all lowercased in the command when there are any disabled arenas in the rotation. However, still not able to join with short name definitions. I.e. typing 'spl' to join 'spleef' when the first arena in the rotation is disabled. It outputs ```Error: Arena disabled, please try again later!``` when it should skip over to the next available arena in the rotation. Problem related to arena name = shortcut name, whereas if that matching named arena is disabled, it breaks the shortcut that shares the exact name?

Also, you seem to have broke shortcut name capitalization when listing arenas. It now displays capitalization or lowercased randomly instead of following how it is set in the config.
![link](http://i.imgur.com/w8OH2dT.png)

**Comment by slipcor** [comment]
yes, all arenas "under a definition" are forced to lowercase. I will solve this differently -.-

**Comment by mibby** [comment]
@slipcor Still not fixed and introduced a new bug. :(  

Tested with this shortcut configuration with the first arena in the rotation 'Spleef' disabled.
```
shortcuts:
  Spleef:
  - Spleef
  - Spleef2
  - Spleef3
```

Arenas no longer display lowercased when typing```/pa list```. So that's great. :D

I can join with ```/pa spleef``` but I can *not* join with it capitalized, ```/pa Spleef```. States the arena does not exist. ```/pa SPLEEF``` works though so related to exact name definition? Even with all arenas enabled in the shortcut rotation, I am not able to join with ```/pa Spleef```. Turning on PA duty mode, I am able to. So shortcut issue?

I can not join with short name definitions, i.e. ```/pa sple``` to join Spleef. When the first arena in the shortcut list is enabled, I am able to.

**Comment by slipcor** [comment]
well yeah.... I might have hack in that it still works even if the desired arena name equals the arena name -.-

**Comment by slipcor** [comment]
oh or something else, let me try something

**Comment by slipcor** [comment]
hmm can you plz do a debug? I don't see anything obvious

**Comment by slipcor** [comment]
I actually might have found it. I only advanced to the next arena available if the arena name was not in the definitions :D

**Comment by mibby** [comment]
Confirmed fixed.
