### ISSUE TITLE
Mod Turrets

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#206]
The Mod 'Turrets' does not work (Server Spigot 1.8.8). In the log file of the server, the following entry appears: http://pastebin.com/rzS6KX7s. The settings in the Areaname.yml are:

   turrets:
     maxdegrees: 90.0
     MinInterval: 2

and (spawns :)

   turret: Custom_Island, 82,76,54,180.729248046875,2.0999948978424072

The standard as "Type" filed arrows achieve no effect. From the player's perspective the view.flickers.

Moreover, it is not apparent in the documentation how to deposit the "Type" of "Turret"... :)

-------------------

Der Mod 'Turrets' funktioniert nicht (Server Spigot 1.8.8). Im Logfile des Servers erscheint folgender Eintrag: http://pastebin.com/rzS6KX7s . Die Einstellungen in der Areaname.yml sind:

  turrets:
    maxdegrees: 90.0
    mininterval: 2

und (spawns:)

  turret: Custom_Island,82,76,54,180.729248046875,2.0999948978424072

Die standardmässig als "Type" hinterlegten Pfeile erzielen keine Wirkung. Aus Sicht des Spielers flackert die Ansicht. 

Außerdem ist aus der Dokumentation nicht ersichtlich wie man den "Type" hinterlegt. :)))

Ansonsten eine hammergeile Idee, wenn sie denn funktioniert xD

**Comment by slipcor** [comment]
Well the error clearly points to the "maps module", I will look into this

Aber der Fehler ist doch klar wegen dem Maps modul :P Ich schaus mir an!

**Comment by CCCCarsten** [comment]
Thanks!
Danke! :)

Ich wollte nur nicht, dass Du nichts zu tun hast xD  :P

Bitte schreibe mir mal, wie man den "Type" ändert.... (also bspw. von "arrow" zu "fireball").

**Comment by slipcor** [comment]
well but still it IS an issue that needs fixing xD

aber ich muss den fehler trotzdem beheben xD

**Comment by CCCCarsten** [comment]
Uhhhhh...... I didn't want to press the button "Close" :). Sorry :)

Außerdem interessiert mich ja auch noch immer die Änderung des "Type"s xD

**Comment by slipcor** [comment]
There is no direct way of changing the values. You have to change the config and reload :D

Es scheint keinen Weg zu geben, es ist nicht so einfach einen Spawn zu ändern, nur in der Config.

https://github.com/slipcor/pvparena/blob/master/doc/mods/turrets.md

**Comment by CCCCarsten** [comment]
Aber **woooooooo**..... verdammte Axt?? :)) WOOOOO setze ich den "type"???? In der config KANN ich dazu nichts ändern.... weil ich den Eintrag dafür dort nicht finde. In der config steht nur das, was ich ganz oben vor zwei Tagen schon gepostet habe.
Aus dem Setup-Teil bei dem Mod "Turrets" geht das nicht eindeutig hervor. Ich habe den Spawn mit 

**/pa (Arena Name) spawn turret** 

gesetzt. ich weiß nicht, wo ich da zusätzlich noch den "Type" (beispielsweise den Fireball!) erfassen hätte können. 

/pa (Arena Name) spawn turretfire   ?
/pa (Arena Name) spawn fireturret   ?
/pa (Arena Name) spawn turret fire    ?
/pa (Arena Name) spawn hallo   ?   ;))

Ich kann den Spawn also wieder aus der config löschen (kein Problem) und neu setzen. Ich muss nur wissen, WIE ich den setze, wenn ich beispielsweise ein FIREBALL nehmen möchte..............

**Comment by CCCCarsten** [comment]
Aehm.......... doch nicht etwa "/pa (Arena Name) spawn **fire**" ??? Fällt mir gerade so ein.... okay, probiere ich morgen am Abend ;))

**Comment by slipcor** [comment]
spawn turretfire

**Comment by CCCCarsten** [comment]
:)) Okay, erst dachte ich ja, Du machst Scherze.... aber klappert tatsächlich! :)) (in meinem Fall "turretBLUEfire". Danke!

**Comment by slipcor** [comment]
yeah is so.

**Comment by CCCCarsten** [comment]
Der Mod klappt ganz gut und ist auch schlichtweg eine geniale Idee! :))
Das einzige, was manches Mal nervig ist, dass der auf der Druckplatte stehende Spieler gelegentlich in so eine Art "Zittermodus" verfällt (schwer zu beschreiben: ....als wenn er feststeckt, und er kann sich dann auch nicht mehr bewegen).

**Comment by slipcor** [comment]
das kann ich leider nicht beheben, das ist clientseitig. sorry. das ist das nächste was ich an bewegungslosigkeit hinbekomme :/

Sorry, that is a client side bug, this is as close as I get to restricting movement :/
