### ISSUE TITLE
Lounge / Spectate overwrites scoreboard restore.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#212]
Spectate / lounge resets player scoreboard to white after a restore happens when teleported to spectator location on death / arena end. Removing StandardSpectate, scoreboards restore fine on arena exit / end.

Slipcor quote;
"People get reset to 'pre join' and then to white because of 'put to spectator'."

**Comment by slipcor** [comment]
@mibby did you see my message? I strongly believe it is caused by ColorTeams or the lack thereof. Might be fixed in the latest _modules version

**Comment by mibby** [comment]
Nope, still broken. Winner's scoreboard is not restored with StandardSpectate used.

**Comment by slipcor** [comment]
@mibby ok then I again need a debug, I added some stuff I think

**Comment by mibby** [comment]
@slipcor Debug.

Run
http://paste.ubuntu.com/18479597/

General
http://paste.ubuntu.com/18479636/

* Player 2 fell out of the world. (i.e. lost)
* Player 1 won.
* Player 1 has a white nametag according to player 2's client.
* Relogging on player 1 does not fix the nametag.
* Relogging on player 2 does fix the nametag.

**Comment by mibby** [comment]
Pasting here so it doesn't get lost.

1) Scoreboard winner nametag white according to losers (when tped through spectatelounge).
2) Scoreboard disappears and reappears when dying and tped to spectate lounge. As well as persists a bit after the game has already ended (tped to old)
3) Scoreboard + colorteams, nametag is not colored the team name when in the lounge. 

slipcor: 2) addendum: scoreboard is set to I game scoreboard for losers 1<x<10seconds after being reset by scoreboards module
I game: ingame

**Comment by mibby** [comment]
RE: 
https://github.com/slipcor/pvparena_modules/commit/455f5c0520b86fad2d3358f4bb3c6cff50c0afac
https://github.com/slipcor/pvparena_modules/commit/8ec255734621d16df4599246a4ea9290dcc98860

Scoreboard score now updates correctly but it displays in lounge (not suppose to) and doesn't show in spectatelounge. 

Also scoreboard doesn't seem to update immediately on key events. (i.e. scoring flag, death, kill) Shouldn't certain tasks force update the scoreboard so it isn't delayed? If not, might be better overall for performance to have the scoreboard only change when certain events go off rather than constant checking every 50 ticks?

What it does fix though is colorteams colors name correctly in lounge and nametags restore properly for the winner on end, presumably because it doesn't have the bugged scoreboard behavior in spectate lounge though since it doesn't display in spectate.

**Comment by mibby** [comment]
RE: https://github.com/slipcor/pvparena_modules/commit/88b9b013fd3b3050e9f45d840a32f1796a60ab73

Same as above. Scoreboard side-bar shows in lounge (not suppose to since it 'builds' as people join teams / the arena, better to display a full scoreboard when it is actually needed) and doesn't show in spectate lounge.

Score also still does not update on the scoreboard when capturing flags and such.

**Comment by mibby** [comment]
SLiPCoR - Today at 7:39 AM
I will try to think about this
plz add something to all open tickets about me deciding to pull this into the core plugin in order to have a sane order at all times
the initial thought behind this was that it was not possible to colorize ppl without a secondary plugin, tagapi or similar
now it's built in so we can build it in, too 😉
and renaming completely does nto work anymore either so let's do this
like... renaming a player to... " "
thus hiding the name
and I think some more things, were possible with colorteams or ,... somthing xD
but that doesnt work so I can just scrap this functinality, or the attempt of it

mibby - Today at 7:42 AM
Well just commit what you have now so it isn't lost. Only thing regarding scoreboards that we shouldn't lose info about is

1) colorteams nametag not coloring in lounge w/ scoreboard
2) no flag capture update event for scoreboard, thus it is delayed / lagged
3) arena end countdown not delaying scoreboard score reset (0,0)
4) People who join spectate directly do not see scoreboard score.  (/pa <arena> spectate) Not sure if they should be allowed to see the score, but they should definitely not be part of the scoreboard player list.(edited)

**Comment by slipcor** [comment]
Alright. I could not test the spectating, but the core mechanics work. Without a runnable, but with proper updating on scoring goals :)

The end reset might be a tough thing, because some things are based on whether a score is there or not, to determine the winner. I will look into this, but for now, most of this error should be fixed for good now :)

**Comment by mibby** [comment]
Few problems.

* Scoreboard shows up in lounge. IMO it should not like old behavior because it is not 'production ready' to watch the scoreboard build itself when players want to play a minigame and join an arena. Better to have the full scoreboard displayed when it is final - when players are actually put in the arena. 

Note; coloring nametag above head to team name does work in lounge. This is intended and works. Just the side-bar scoreboard building shouldn't be displayed in the lounge.

* Players are removed from the scoreboard when they are 'out'. Before, their names turned white on the scoreboard when they were dead/out.

* No scoreboard is displayed when still part of the arena, but dead / in spectate lounge. So you can't watch your team try to win or see progress of alive/dead players.

**Comment by slipcor** [comment]
I will try looking into that - maybe I can set the display slot only when the game start? Not sure if this works though :/

Yeah I think I can try to fix this for team modes at least. This will also mean that the names will stay colored then. But I don't think that will be an issue.

**Comment by mibby** [comment]
Since all scoreboards are handled internally instead of by separate modules now, I will be closing this ticket and will re-open any future scoreboard issues to a new ticket.
