### ISSUE TITLE
Spawn_Eggs

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#218]
A Spawn_Egg which has been saved in classes don't hold its property like spider, creeper and so on. This is almost certainly caused by SPIGOT 1.9.x.

**Comment by slipcor** [comment]
Yep. As of this week, there is no fix available. They did not add a function to fix this yet. Doing it would mean a hell lot of hacking :)

**Comment by CCCCarsten** [comment]
What is your experience? How long the spigot team will work on this bug?

**Comment by slipcor** [comment]
no idea.

**Comment by CCCCarsten** [comment]
![spawn_egg](https://cloud.githubusercontent.com/assets/18105655/16199658/b8d96f02-370a-11e6-8cc6-418fa55d96f4.jpg)

**Comment by slipcor** [comment]
Those things break on every minor/major minecraft update and I would have to release versions strictly to each version to work. Right now I did already do a big move to 1,9, but with this I would have to run 3 versions:

1.9.2
1.9.4
1.10
1.10.1

**Comment by slipcor** [comment]
@CCCCarsten apparently they did it. I just released the last build as final 1.3.3 build and I am now updating the POM for 1.11, and the dependency information overall.

So the next build will fix this! I already tested it, it works thanks to additions to Spigot in December :)
