### ISSUE TITLE
Shortcut name joining issues.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#222]
PVPArena dev 156

Players are able to join specific named arenas even though it is part of a shortcut rotation.

* /pa Spleef2
* Puts player in 2nd spleef arena every time and broadcasts others to join via /pa Spleef2 instead of using the shortcut rotation.

Arena Debug - http://paste.ubuntu.com/18150319/
General Debug - http://paste.ubuntu.com/18150332/

```
use_shortcuts: true
only_shortcuts: true
shortcut_shuffle: true
allow_ungrouped: true
```
```
shortcuts:
  Spleef:
  - Spleef
  - Spleef2
  - Spleef3
```

All arenas in rotation enabled.

When players try to join with ```/pa Spleef```, it alternates between using the shortcut and putting them in the first arena, as if it can't decide to use the shortcut or throw them in the arena with that name.

Ideal behavior is disallowing joining the arena via the arena name if it is part of a shortcut and only allow joining it via the shortcut name.

**Comment by mibby** [comment]
@slipcor Not fixed. Now when players join via the shortcut name, it puts each person in a different arena (in the rotation).

General debug.
http://paste.ubuntu.com/18478764/

Spleef debug.
http://paste.ubuntu.com/18478793/

Spleef3 debug.
http://paste.ubuntu.com/18478811/

* Player 1 typed /pa spleef.
* Was put in the first spleef arena.
* Player 2 typed /pa spleef.
* Was put in the third spleef arena.

```
use_shortcuts: true
only_shortcuts: true
shortcut_shuffle: true
allow_ungrouped: true
```

```
shortcuts:
  Spleef:
  - Spleef
  - Spleef2
  - Spleef3
```

**Comment by mibby** [comment]
Confirmed finally fixed.

**Comment by mibby** [comment]
REOPEN PLEASE.

Disabled spleef and spleef 2. Spleef 3 is enabled. Typing ``/pa spleef``` outputs arena disabled, please try again later.

**Comment by slipcor** [comment]
You know what I need from you :)

**Comment by mibby** [comment]
http://paste.ubuntu.com/18789242/

**Comment by slipcor** [comment]
I can not reproduce this. I setup 3 arenas Test-> Test, Test2, Test3 and joining with "pa test" works, I get put into the arena that is available, tested enabled test2 and test3 - ACTUALLY "test" doesn't work if Test is enabled....

**Comment by slipcor** [comment]
I actually did fix an issue about a proper (case insensitive) name match being treated lower than a (later) beginning or ending arena name match.

And yeah finally I fixed that a proper shortcut is always priorized and treated intelligenty, no longer chooses the best/last fitting arena by NAME match, a shortcut definition catch always takes priority now!

**Comment by mibby** [comment]
@slipcor =/ You fixed the joining issue when the first two arenas are disabled in the shortcut rotation, but broke the arena shortcut cycling and announcement.

http://paste.ubuntu.com/19415502/

All 3 arenas are enabled.
```
shortcuts:
  Spleef:
  - Spleef
  - Spleef2
  - Spleef3
```

Joining via ```/pa spleef``` outputted ```Type §e/pa Spleef3§b to join!``` rather than the shortcut name and always put players in the third map. It never cycled maps when playing and winning/losing in it.

**Comment by mibby** [comment]
RE:

Still kind of broken.
http://paste.ubuntu.com/19627671/

> Server starts up with all 3 arenas in the shortcut rotation disabled.
> Listing arenas in-game shows that shortcut name as red. Trying to join states the arena is disabled.
> Enabled first map in rotation - 'spleef'. 
> Listing arenas in-game, shortcut name is still red. (Should be white - at least one arena in the rotation is enabled!)
> Have to enable all 3 arenas in shortcut before name turns white.
> Name finally white, am able to join.
> Disabled all arenas except the third. 
> Name is still white, still able to join.
> Disabled all arenas except the second.
> Name is red. Can't join.

**Comment by slipcor** [comment]
I think I know what happened.... and I think I should have fixed it!

**Comment by mibby** [comment]
I believe everything is working as intended now. :D Finally all fixed. Will re-open if I discover it is not.
