### ISSUE TITLE
More than one arena start announcement

### ISSUE THREAD

**Issue by ChrisLane** [slipcor/pvparena#223]
I'm getting more than one "arena is starting" message sometimes and I assume this may be due to the arena join warmup.

So player 1 tries to join the arena and has to wait 5 seconds and during those 5 seconds, player 2 tries to join. So I'm assuming there's no check for who's joining the arena as well as who's in the arena and that this is the cause.
A lot of assumptions so I will to replicate with join warmup disabled.

Arena debug log: http://paste2.org/WKXsYmjf

**Comment by slipcor** [comment]
That could actually be a thing. When warming up, you are not yet part of the arena and the arena did thus not start :) I will look into this!

**Comment by slipcor** [comment]
please check the latest build of modules:

v1.3.3.162 - [Announcements] - address github issue #223

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/130/

**Comment by ChrisLane** [comment]
New logs after the new version didn't work for me: http://paste2.org/EV3HO12v

**Comment by ChrisLane** [comment]
There are now no arena start messages! An improvement I guess :p

debug: http://paste2.org/XDKCtHwe

**Comment by slipcor** [comment]
v1.3.3.193 - [Announcements] - and this is why you don't do negative method names

**Comment by ChrisLane** [comment]
New debug..I don't know which issue to comment on anymore O_O

http://paste2.org/B4x1acvw

**Comment by slipcor** [comment]
v1.3.3.214 - [Announcements] - address github issue #223
