### ISSUE TITLE
Double output when right clicking ready block while in the lounge.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#224]
Debug.
http://paste.ubuntu.com/18479897/

Joined CTF by myself. Right clicked the ready block once and the 'you are alone in the arena!' output occurred twice.

Had another player join CTF on the opposite team but not ready up. Right clicked the ready block again and the 'your team is alone in the arena!' output occurred twice.

**Comment by slipcor** [comment]
I think this is a 1.9 bug, iirc they throw two events, one for each hand, with no way of knowing which one it is. This might only happen for right click though and I have no idea what to do about it

**Comment by mibby** [comment]
@slipcor See my comment here posted on MobArena regarding double output. WorldGuard pushed a fix for it a while back, could be used in PA too if you use the same method for listening clicks.
https://github.com/garbagemule/MobArena/issues/299#issuecomment-220866730

**Comment by mibby** [comment]
@slipcor This broke readying up in the lounge when right clicking the ready block with your fist. But it did fix the double output when right clicking, at least right clicking with an item in your hand. 

Debug
http://paste.ubuntu.com/18676688/

**Comment by slipcor** [comment]
Seems the world guard fix did not help here. So what do I do now?

**Comment by mibby** [comment]
@slipcor That works. Confirmed fixed now. :D
