### ISSUE TITLE
Support '/pa l' as a shortcut alias for '/pa leave'?

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#225]
Similar to how MobArena allows ```/ma l``` to leave rather than typing the whole word?

**Comment by mibby** [comment]
@slipcor ```/pa -l``` works but ```/pa l``` does not. The latter just outputs you are already part of <arena>.

**Comment by mibby** [comment]
@slipcor Not working as intended. ```/pa l``` states 'you are not part of an arena!' when typing while in the lounge.

http://paste.ubuntu.com/19414318/
http://paste.ubuntu.com/19414344/

```/pa -l``` and ```/pa leave``` still work as intended.

**Comment by slipcor** [comment]
1) there is no debug showing this message being sent (ERROR_NOT_IN_ARENA)

2) it works on my test server, actually that is what I tested , I never tested without lounge xD

plz try again <3

**Comment by mibby** [comment]
Arena
http://paste.ubuntu.com/19617855/

General
http://paste.ubuntu.com/19617887/

**Comment by slipcor** [comment]
I still have no explanation as to why there is no debug output :(

however, I think I am fixing it right now. Only admins (duty / override people) were affected, maybe.

**Comment by mibby** [comment]
Confirmed works now. :)
