### ISSUE TITLE
REFILLFORKILL is swapping your class with the person you killed instead of refilling your own class contents.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#227]
https://github.com/slipcor/pvparena/commit/f3299e89bdb07529c6e11dd5b470ee83fb647097

Behavior should be to restore your inventory contents when getting a kill, not swap classes with the person you killed. i.e. refill arrows used when getting a kill

**Comment by slipcor** [comment]
April fool's! xD

**Comment by mibby** [comment]
:s

**Comment by mibby** [comment]
Refill and health restore on kill confirmed fixed, working as intended now.
