### ISSUE TITLE
onEntityRegainHealth every half second when SATIATED.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#231]
http://paste.ubuntu.com/19628475/

When players are fully satiated, regen occurs every half second instead of natural vanilla speed.

**Comment by slipcor** [comment]
But I am not altering that. If that is an issue, please set the saturation start amount to like... 10 or lower

**Comment by mibby** [comment]
But 20 is full hunger due to hunger bars allowing for half full like hearts, as well as being your default setting. :P So problem is somewhere else?

**Comment by slipcor** [comment]
there are two distinctly separate things:

1) hunger - which is 1 to 20 and reflected in 10 icons showing how much you ate and how full your stomach is :P
2) satiation, which also is 1 to 20, I believe, and is not shown anywhere but is calculated internally by WHAT you eat, it is added based on what KIND of food you eat, and when that drops down to 0, you start losing hunger, iirc.

And if you are fully satiated (no matter how hungry or hurt you are) you will regain health quicker :)

**Comment by mibby** [comment]
Commit nuked since it is not possible to lock saturation. Will just have to be a problem people work around.
