### ISSUE TITLE
Potion disappeared

### ISSUE THREAD

**Issue by CCCCarsten** [slipcor/pvparena#232]
If a potion slot is active and a player clicks on the iron block (ready for entering the arena), then the potion is gone. Not only invisible (as before, #166 ), but really gone :)).

Ein im Slot aktiver Trank verschwindet, wenn man zum Betreten der Arena auf den Eisenblock klickt. Wenn ich das noch richtig in Erinnerung habe, war der Trank früher nicht wirklich weg. Mit Einsatz von pvparena #184 und den Mods #139 unter Spigot 1.10 ist er das aber nun. :)

**Comment by slipcor** [comment]
No idea what to do about that, I cancel the interaction event, what should I do more? I hope they fix it soon :/

Keine Ahnung was ich nun machen soll... ich cancel doch alle Events was soll ich noch machen? :P Vielleicht fixen die das ja bald

**Comment by CCCCarsten** [comment]
Take the next free slot and turns it up to "active"? Or always the first slot?

Vorschlag: Setze in der Schnellstartleiste den nächsten freien SLOT auf aktiv? Oder nimm grundsätzlich den SLOT 0 (den ersten) auf aktiv... dann kann ich das selber anpassen :)
