### ISSUE TITLE
Ready block not starting the game.

### ISSUE THREAD

**Issue by ChrisLane** [slipcor/pvparena#233]
PvPArena Version: v1.3.3.185
Debug log: http://paste2.org/BB7AILyY

Players click the ready block (iron block) which is registered in the log but nothing is done about it.
This issue does not happen all the time but I don't know the conditions to recreate it.

**Comment by slipcor** [comment]
1.9 fix "out: offhand!" - please fix your code :P

**Comment by ChrisLane** [comment]
hehe silly me
