### ISSUE TITLE
Two arena join announcements per player

### ISSUE THREAD

**Issue by ChrisLane** [slipcor/pvparena#234]
**Announcements module**
I have arena warmup join enabled.

When a player joins an arena there are two "{player} joined the arena" messages. 
The first appears when the player runs the arena join command and is waiting to join.
The second appears when the arena is teleported to the arena lounge.

Debug log: http://paste2.org/KCgw61Xh

**Comment by slipcor** [comment]
Sounds like the other issue about double announcements. Will try to fix :)

**Comment by slipcor** [comment]
Can you try the latest module build of Announcements?

v1.3.3.194 - [Announcements] - address github issue #234 - only announce once

**Comment by ChrisLane** [comment]
Here's the new debug plus the classic TP to the wrong place XD

http://paste2.org/B4x1acvw

**Comment by slipcor** [comment]
might be fixed with v1.3.3.214 - [Announcements] - address github issue #223 too

**Comment by ChrisLane** [comment]
Don't seem to be getting any announcements at the moment despite the mod file being in the "mods" folder and being enabled in the config.

I can see that it's not loaded in this debug so I'll look into startup configs etc. in a bit http://paste2.org/ZpkpzHcy

**Comment by slipcor** [comment]
Yes, even if it does skip it should announce "parseJoin ... " and THAT it skips!
