### ISSUE TITLE
Feature Request - ItemOnKill

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#237]
Requesting a way to give an item on kill. Such as providing a single arrow when you kill someone.

Refillonkill does not work because it restocks your class inventory contents. Meaning if you pick up someone's gear on the ground and get a kill, your inventory is wiped. i.e. pickup 2 arrows (have 3) kill someone, back to 1 arrow that comes with your class.

**Comment by slipcor** [comment]
the goal "KillReward" could serve for this specific use case, you could set up "tiers" of "one arrow, two arrows, three arrows" and people would ascend by killing (and basically receive the class items of that "arrow count")

So, a new module or can you use KillReward?

**Comment by mibby** [comment]
Well, the problem with killreward that I can see, you have to specify what to give for every kill. I just want to provide a single arrow if someone gets a kill, for every kill they get.

**Comment by slipcor** [comment]
yeah okay I get that. Let's see :)

**Comment by slipcor** [comment]
Tested locally it should work :)

**Comment by mibby** [comment]
How would one go about setting an item on kill via command? I tried ```/pa <arena> set itemsonkill arrow``` but it said 'null is no proper item'.

**Comment by mibby** [comment]
Confirmed working as intended with ```/pa <arena> set itemsonkill inventory``` with the items you want to provide on kill in your inventory at the time of setting.
