### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by shootcraft** [slipcor/pvparena#238]
Why in teamdeathmatch or teamlives, same teammate able to damage each other ?

**Comment by slipcor** [comment]
because "teamkill" is set to true? :)

**Comment by shootcraft** [comment]
how to set to false ?

**Comment by shootcraft** [comment]
is there any way to respawn with inventory but not with initial gear because this will cause the armor not receive damage and some consumable items such as potion will be unlimited

**Comment by slipcor** [comment]
1) /pa [arenaname] set teamkill false

2) so you want to respawn with armor but different and not with the initial potions? I am afraid, no.

**Comment by shootcraft** [comment]
Something like after respawning, player will get the armor that had received damage and potions or items that consumable  so it wont duplicate

**Comment by slipcor** [comment]
hang on but it does not duplicate in that sense that you have 2 sets of armors, right? Your issue is that they get "fresh" armor and all potions and things?

okaaaay there might be a solution for you:

1) set 'refillInventory' to false (so it does not refresh)

2) fill your inventory with the class items (how many are there? I might look into getting an "ALL" setting for this) and do /pa [arena] set keepOnRespawn inventory

This way the arena should not remove the items on respawn, and should not restock the items on respawn :)

If this does not work out, give me a shout, I will look into fixing this, because it should :P 

If you need the "ALL" codeword for the setting, that should be a quick thing!

@shootcraft

**Comment by shootcraft** [comment]
thanks for helping me :), when will be the official update for pvparena ?

**Comment by slipcor** [comment]
it is there :)

v1.3.3.187 - allow to set keepOnRespawn to "all" to, yes, keep all items

https://ci2.craftyn.com/job/PVP Arena/

**Comment by shootcraft** [comment]
Thank you !!, I have downloaded and test it, returnbackinitialgear has to disable ? how to use it ?

**Comment by slipcor** [comment]
"customReturnsGear" should be false, if not:

/pa [arena] set customReturnsGear false

**Comment by shootcraft** [comment]
it showed unrecognized material : all
items:
  excludeFromDrops: none
  keepOnRespawn: all
  minplayers: 2
  random: true
  rewards: none
  takeOutOfGame: none

**Comment by slipcor** [comment]
please try v1.3.3.197 :)

**Comment by shootcraft** [comment]
It showed the same unrecognized materials : all , I am using 1.3.3.197

**Comment by slipcor** [comment]
okay and to be clear. it does not work? It could actually still throw this warning but work :) I will try to test on my laptop

**Comment by shootcraft** [comment]
Yes, it still not working

**Comment by slipcor** [comment]
Okay I debugged this and I forgot a place in my code where I still checked for the items specifically. Here you go! #199 should fix it, I confirmed it on my laptop :D

https://ci2.craftyn.com/job/PVP%20Arena/

I gave myself gold armor, got killed, and the armor was still damaged, and yeah; I got all items back, not not the "fresh" armor :)

**Comment by shootcraft** [comment]
Awesome, it works perfectly, thanks a lot : )

**Comment by shootcraft** [comment]
I really appreciate it and it really changed my server function a lot

**Comment by shootcraft** [comment]
I just found a bug, player die at last will not get back their stuff, example final kill of the player on the dead person will not get back it stuff . it might because the computer has marked the loser leaving the arena already and do not respawn back player stuff when got final killed

**Comment by slipcor** [comment]
if you want that you need to set "customReturnsGear" to true :)

**Comment by shootcraft** [comment]
this will cause the game to be the same at like last time and player will stay in initial armor whereby it is undamaged

**Comment by shootcraft** [comment]
why loser of the game lose stuff and only winner can retain it stuff

**Comment by slipcor** [comment]
oh you are right, if you set it to true, people will always get the fresh gear... dammit... okay I need to think about this.

About the loser thing - well ... that will tie in with "returnsGear" - this initially SHOULD ONLY decide that people get their INITIAL gear back after playing, even when losing - and well if you lose, you lose :) that was the risk of playing with your own stuff. It is up for grabs ;)

Yeah I will add some configurations for proper decisions on that part... I hope I cover all cases

**Comment by shootcraft** [comment]
Thank you so much, I will be awaiting it in future

**Comment by slipcor** [comment]
@shootcraft hey! I think this should work now. refillCustomInventory is the setting "on respawn" and the "returnsGear" setting is "on exit" so if you die and have 3 lives, you get your stuff back twice, but then you lose it entirely :)

please verify!

**Comment by shootcraft** [comment]
Thanks for updating and fixing, I appreciate it :) do u have any other plugin except pvparena ?

**Comment by slipcor** [comment]
hmmm I am contributing to MobArena - it is not made by me but I am currently helping to develop things, it is an awesome plugin that works great for years!

I have "pvpstats" which basically is SQL hook for player stats. Kills, killstreaks, deaths, etc.

I have "BanHammer" which is a little plugin to mute and then kick people who spam and say bad things xD
