### ISSUE TITLE
Debug output at start-up is using 'general' language string instead of standard plugin prefix.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#240]
The debug status output at start-up is using the 'general' prefix language file string instead of a standard plugin prefix, i.e. [PVP Arena].
![link](http://i.imgur.com/1oZRRa3.png)

So if you changed the language string at all, it would display the change.
![link2](http://i.imgur.com/BHTBCKD.png)

Shouldn't it remain consistent with with the other prefix as a plugin system message?

**Comment by slipcor** [comment]
He is alive !!! 

Yes, you are correct. It should look like the other messages you see there :)

**Comment by mibby** [comment]
Confirmed fixed, thanks.
