### ISSUE TITLE
Scoreboards not found ??

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#242]
Hallo Slipcor,

pa build 197
pa mods build 149

I thinks, you forget to add scoreboard somewhere because i can't install the module ^^'

danke,

**Comment by slipcor** [comment]
No, the scoreboard module was implemented into the main plugin, everything should be working as before, in fact, it shoudl work NOW contrary to before :)

**Comment by Oruss7** [comment]
Ahh okay =)
The documentation is up to date? How use it now?

**Comment by slipcor** [comment]
the same way :D it's the same config setting. no I did not update the documentation xD

**Comment by slipcor** [comment]
oh I added a new config!! 

uses.scoreboard

That is the thing to do :D

**Comment by Oruss7** [comment]
Thanks xD
