### ISSUE TITLE
How to disable the updater?

### ISSUE THREAD

**Issue by Sikatsu** [slipcor/pvparena#244]
How can I disable this message: http://prntscr.com/cyczeb ?

update:
  mode: download
  type: beta
  modules: true

**Comment by slipcor** [comment]
https://github.com/slipcor/pvparena#update-checker

set

modules: false
mode: off

**Comment by Sikatsu** [comment]
I actually meant to turn off the notify message on join, not the whole updater, sorry.

I thought ''download'' would just download but not notify on join, am I right? If so, it didn't work.

**Comment by slipcor** [comment]
yes. if you have it on download but it still notifies, then I need to fix this on my end :O

I will check this!

**Comment by slipcor** [comment]
v1.3.3.217 - do not nag people to update if updater type DOWNLOAD is selected - addresses github issue #244

We will not know if this works until I release a newer version xD but I am quite sure I caught the bug!
