### ISSUE TITLE
/pa arenaclass is broken

### ISSUE THREAD

**Issue by Sikatsu** [slipcor/pvparena#246]
/pa arenaclass isn't working. 

When using /pa arenaclass it doesn't show any classes and when using /pa arenaclass Archer it doesn't give the right class. No errors given.

**Comment by slipcor** [comment]
Von meinem Samsung Galaxy Smartphone gesendet.
1) are you in an arena when trying this command?
2) are you sure that this is the class name? (Case matters)
3) please share your config, e.g. www.pastebin.com - it definitely should be working


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/slipcor/pvparena","title":"slipcor/pvparena","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/slipcor/pvparena"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"/pa arenaclass is broken (#246)"}],"action":{"name":"View Issue","url":"https://github.com/slipcor/pvparena/issues/246"}}}

**Comment by Sikatsu** [comment]
Yeah I closed it because I found out theres a setting within the config for it :P
