### ISSUE TITLE
PvP Arena randomly broke, player lost his inventory

### ISSUE THREAD

**Issue by Sikatsu** [slipcor/pvparena#248]
Players were playing the FreeForAll arena, when suddenly they could not attack eachother anymore.
When they used /pa l and used /pa j again, an error occured and their inventory was wiped.

I could reproduce it.

This is the error that came up: http://pastebin.com/EmiWH1pj

Hope this can be fixed, this is the second time.

**Comment by Sikatsu** [comment]
So both the issue with inventory wipe and that they can't attack eachother should be fixed? :)

**Comment by slipcor** [comment]
I think so

**Comment by Sikatsu** [comment]
Will test later today and let you know if it still occurs.

**Comment by Sikatsu** [comment]
Players can't attack at all lol, no error pops up neither a message.

**Comment by Sikatsu** [comment]
Any idea when you can fix this? As currently I can't use it :/ @slipcor

**Comment by Sikatsu** [comment]
Shit. It works after all, made a mistake. 

As for the inventory wipe, time will tell. Before, players were complaining a lot about it, so we will see it soon.

**Comment by Sikatsu** [comment]
@slipcor

Nope, huge problem. We announced a pvp battle against staff and many people joined. Atleast half of them lost their inventory now. Could you please fix this? On a survival server this is really really bad

**Comment by Sikatsu** [comment]
Still without pvp arena, are you there?

**Comment by slipcor** [comment]
me.jacobculley.customgui

this is the plugin that is messing up, please inform them about that

**Comment by slipcor** [comment]
sorry for the late reply, somehow I did not get notifications /:

**Comment by Sikatsu** [comment]
The developer of customGUI said it's an issue with pvparena, not customgui..

Also, I use the same system for MobArena with CustomGUI and it doesn't give any issues at all. I saw you were part of the MobArena plugin on bukkit too, maybe you can check what exactly is different from your plugin?

MobArena plugin doesn't give any issues.

**Comment by slipcor** [comment]
Was this error you linked related? Then I can only tell you that this error is not at all caused by PVP Arena, it is before the command gets handed TO my plugin, that the customGUI plugin does get an error and thus my plugin does not even receive the command.

If they think it is my mistake, I would like to know how I could possibly cause an error that is not even handled by my plugin, code wise....

**Comment by Sikatsu** [comment]
It was the only error I could find related to PvP Arena. It is an issue that is very hard to reproduce, however since I work with the signs instead of CustomGUI, it's still being an issue after leaving the arena sometimes.

**Comment by slipcor** [comment]
Okay please keep an eye out for when this happens again and check the exact time, if there is an error when this happens. If you found a way to cause this with certainty you could run a debug.

Well if your server can handle it, you can generally run debug with /pa debug all

And as soon as the error happens you stop it /pa debug none

and then check the latest minutes of debug - however the debug will be very spammy :/ so the more precise the less spam you have on your hard drive
