### ISSUE TITLE
Blood particle on hit

### ISSUE THREAD

**Issue by Sikatsu** [slipcor/pvparena#249]
Are you able to add a blood particle on hit as config option?

![image](https://cloud.githubusercontent.com/assets/5664135/19861094/919206f4-9f8b-11e6-865c-60f68f2262a4.png)

**Comment by slipcor** [comment]
I will have to look into this but the last time I checked there is no built in particle API, everyone uses some kind of third party plugin, and I would hate to have that as my solution :/

I will keep you posted

**Comment by Sikatsu** [comment]
Alright! :)
