### ISSUE TITLE
Incorrect fly speed being set.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#250]
@slipcor RE: https://github.com/slipcor/pvparena/commit/c67e4a6614467bb6f8bfeee56f7c236508154ed7

See comment here. https://github.com/slipcor/pvparena/commit/4f75803c3a38258dff8a409482126223505d9215#commitcomment-19625952

**Comment by slipcor** [comment]
@mibby it should be fixed, right?

Sorry for the late reply, somehow github does not send emails any more to notify me of new stuff :(

**Comment by mibby** [comment]
Sorry, been caught up with work. I'll give it another test tomorrow now that I have a stable 1.11 environment. <3

**Comment by mibby** [comment]
@slipcor Unfortunately still seems to be broken as of this commit. (dev 209) https://github.com/slipcor/pvparena/commit/cee19551cf2b56e0639c342cb28d0bee52243b85

I reset the config defaults to -10 (per the newest commit) and tested a very extreme user case. Set my walk speed to 10 outside the arena so I can tell movement is fast and unaffected. Then I joined an arena. My walk speed was still set to 10 in the lounge - fast movement running around in the lounge. Leaving the arena lounge with ```/pa leave```, my walk speed was reset to a slow value - in otherwords, my former value was not restored on arena leave.

Back to dev 206 until speed setting / restoring bugs are ironed out. :(

**Comment by mibby** [comment]
Closing since fly / walk speed isn't being touched by PA anymore.
