### ISSUE TITLE
Poison Arrow Effects persists after kill

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#251]
When a player is killed, he still have potion effect (or arrow effect). 
That's annoying when potion effect is poison ><

Thanks

**Comment by slipcor** [comment]
Wow really.... is this an effect by a class effect or just by being hit?

How did they get this effect?

**Comment by Oruss7** [comment]
arrow

**Comment by Oruss7** [comment]
Working in last dev

**Comment by Oruss7** [comment]
What happening ? effect still present after player respawn.... i have lastest dev build.

**Comment by Oruss7** [comment]
Happening with POISON ARROW, potions works fine.

**Comment by slipcor** [comment]
I will have a look into this :/

**Comment by slipcor** [comment]
okay I had to add a delay just for the arrows apparently. yay fixed!

**Comment by slipcor** [comment]
https://github.com/slipcor/pvparena/commit/e5690d85699d5a4189659471e14ec1e2b1550a8d

**Comment by Oruss7** [comment]
Working. Thanks.
