### ISSUE TITLE
Class load non-functional.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#252]
PaperSpigot dev 953 (MC 1.11)
PVPArena dev 206

Typing ```/pa <arena> class load <class>``` does not provide you with the class loadout for testing. Wipes your inventory, but doesn't provide the items. No errors in console.

**Comment by Oruss7** [comment]
Same.

**Comment by slipcor** [comment]
@mibby @Oruss7 

you guys know the drill. I need a debug :P

I will try to reproduce this

**Comment by slipcor** [comment]
guys, there even was an error. I am disappointed :P fix is incoming

**Comment by Oruss7** [comment]
Thanks you @slipcor !

**Comment by mibby** [comment]
There was an error? I never got one. :( I feel scammed.
