### ISSUE TITLE
Better Gears: How configure it ?

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#253]
Can you explain more on the doc.
We don't understand this mod ='(

Thanks !

**Comment by Eredrim** [comment]
> These are to activate/deactivate armor enhancement

    head - alter the head slot
    chest - alter the chest slot
    leg - alter the leg slot
    foot - alter the foot slot
    onlyifleather - only alter leather inventory contents

How can I use it ? Is it a command or a config node ? Can you give me a concrete example to have a red legging ?

**Comment by slipcor** [comment]
yeah it is a config node, you set "leg" to "true" (either in the config section under "bettergears" or with a command:

/pa [arena] set leg true

and then by default when you reload the config ( /pa reload ) it should turn the leg armor into red cloth leggins

**Comment by Oruss7** [comment]
**bug**: better gears remove enchants on gears ... 

Suggestion: can we display color when we choose class on lobby ? Seems better gears color only in-fight.
