### ISSUE TITLE
Remove arrows on players after dies

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#254]

**Comment by slipcor** [comment]
You mean during the game or after the game?

**Comment by Oruss7** [comment]
during the game. Some class have invisibility, but one arrow and everybody see them xD

**Comment by slipcor** [comment]
haha okay I will check if I missed doing that :) fix should be incoming soon!

**Comment by slipcor** [comment]
update and set "player.removearrows" to true :)

**Comment by Oruss7** [comment]
not working ='( 
pa v1.3.3.217

`removearrows: true`, i check the config file.

**Comment by slipcor** [comment]
Well if you wait long enough, they will break it again. This should work for all versions 1.9* and 1.10* and 1.11*

**Comment by slipcor** [comment]
Yep, I have not found API for that at least :/ I just looked through the spigot 1.11.2 Jar and there is not method about Players (or anything in that class inheritance tree) about Arrows, so i will assume that it is not done yet
