### ISSUE TITLE
Task causing lag and players timeout

### ISSUE THREAD

**Issue by bloggy** [slipcor/pvparena#255]
Paper Spigot: This server is running Paper version git-Paper-910 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
pvpArena Version: Loading pvparena v1.3.3.209

See screenshot of timings:
http://i.imgur.com/RiLHcCs.png

This task caused a big lag and players timed out:
pvparena::Task: net.slipcor.pvparena.core.Tracker (interval:72000)

What is this task doing and will you be able to fix it?

**Comment by slipcor** [comment]
What do those times mean exactly? It is a short HOURLY check that pings my homepage to see who is using which version. It should not be an issue.

You can turn it off by setting "tracker: false" in the main config
