### ISSUE TITLE
BetterGears

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#257]
Better gears remove enchants on armors...  but color work fine ^^

**Comment by slipcor** [comment]
please elaborate. When is it removed? Well technically bettergears is there to change the enchantment so ... yeah that is a thing the module does by definition. I can try to keep existing enchantments, give me a minute.

**Comment by Oruss7** [comment]
i need to config manually enchants ?

**Comment by Oruss7** [comment]
Suggestion: can we display color when we choose class on lobby ? Seems better gears color only in-fight.

**Comment by slipcor** [comment]
I am sorry but I have no idea what you are talking about.

https://github.com/slipcor/pvparena/blob/master/doc/mods/bettergears.md

The enchants are set with:

/pa !bg [name] level [number] - set the protection enchantment level 

I will look into this. Yes, as of now, the coloring is only done when starting the game.

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

**Comment by Oruss7** [comment]
Actually, i save class with /pa class save command. I wear armor with enchants. When better gears is activated, i need to re-set enchants with /pa !bg [name] level [number] ???

**Comment by slipcor** [comment]
yes. the bettergears module wholely overrides the armor, with colored leather and an enchantment . you can specify to only do it for individual items that are leather anyways, but standard is that it replaces the armor. And you can not add more enchantments than what is hardcoded in the game. Bettergears is a very special module for a special application. maybe it is the wrong module to use?

**Comment by Oruss7** [comment]
I just want color leather and keeps my armor as defined be the class.  Is exist an other module to do that ?

**Comment by slipcor** [comment]
no. you might want to manually color your armor then, and split the classes to e.g. blue_ranger and red_ranger or similar. BUt I have an idea, I can try changing the way the module does things to "only color" if no level is set?

**Comment by Oruss7** [comment]
we do. But, with **_switch class in game_** actived, red players can pick up _blue_ranger_ ><
That's the reason we want use BetterGears =)

**Comment by slipcor** [comment]
mhhhhh can't you restrict those classes= with betterclasses?  xD

**Comment by Oruss7** [comment]
-_-

**Comment by Oruss7** [comment]
To summurize : how to take 6 hours to make a good config instead of just using BetterGears in three commands

**Comment by slipcor** [comment]
whaaaa? ^^

**Comment by Eredrim** [comment]
So, I resume the discussion. Oruss7 and me, we need to use BetterGears on enchanted armours. Currently, it is not possible (I didn't try the latest builds).
But you will say : "Why do you not use BetterClasses for compensating enchants ?" For two reasons : 
- We need enchants which are exclusive to armours like protection, projectile protection, aqua affinity, thorns or frost walker.
- It is really easier and faster to change enchants effects via BetterGears than via BetterClasses

**Comment by slipcor** [comment]
Hmm can you please line out exactly how it should work out config wise? I am not sure I understand the specific use case you have.
What do you want to set? Individual enchants for armors? Per team? If not, why not just save the enchants in the class and remove the setting of that armor piece in the betterclasses/bettergears module?

**Comment by Eredrim** [comment]
> If not, why not just save the enchants in the class and remove the setting of that armor piece in the betterclasses/bettergears module?

It is exactly I want to do : create a class with enchanted armor pieces and change their color with betterGears. But when I start the arena, the colors are correctly setted but the enchants disappears.

**Comment by slipcor** [comment]
Oooooh now I understand! Thanks for the clarification, I will try to fix this, this is a bug that should be easy to fix :)

**Comment by slipcor** [comment]
Thanks for the clarification again, I finally was able to track down the bug and fix it!

v1.3.3.236 - [BetterGears] - Do not overwrite existing leather enchants when coloring

Grab it here: https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/dist/target/files.zip
