### ISSUE TITLE
Liberation: scoreboard

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#258]
Well, scorebord display 1:1. 

May be display player who are in prison ?

Thanks !

**Comment by slipcor** [comment]
@Oruss7 so how would this look? I added the backend method to add a custom scoreboard. Will this be on top of the scoreboard?
```
Jailed:        199
slipcor        198
Oruss          197
---------------101
ChrisLane      2
mibby          3
slipcor        0
Oruss          0
```

Or do you want the jailed to not be on the normal scoreboard?

**Comment by Oruss7** [comment]
Not be on the normal if possible :)

**Comment by slipcor** [comment]
I will try my best - I cannot test it though because it needs 3 ppl sooooooo I will have you testing it :D

**Comment by slipcor** [comment]
good luck! :D

**Comment by Oruss7** [comment]
@slipcor Hummm... work but when a players are liberated, scoreboard don't update correctly
