### ISSUE TITLE
Handicap module to balance games if team members leave.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#266]
Would it be possible to create a handicap module to balance games if someone's team becomes unbalanced and you don't allow for late joining? For example, providing a fraction / percentage of health boost to players. 

i.e. 2v2

If it becomes 2v1, give the person by himself double the amount of hearts.

i.e. 3v3

If it becomes 3v2, give a 30% heart boost to the team with less players.

Handicap could be provided by additional hearts (full hearts or temporary hearts), damage boost, speed boost, providing effects to a player, etc. Anything to help the team at a disadvantage.

**Comment by slipcor** [comment]
Good luck testing this, I literally cannot as this needs 3 people :) It automatically does this no matter what the team sizes are, if you add the module, it adds effects based on your setting, HEALTH by default, the rest is done with potion effects, sooooo please test the health :D

v1.3.4.281 - [Handycap] - untested build - use with caution!

**Comment by mibby** [comment]
Closing ticket. I personally no longer have a need for this module. Feel free to re-open if this is something you do want to implement or expand further.

**Comment by Oruss7** [comment]
Solution: Players are banned if they leave the game before end.
