### ISSUE TITLE
NametagEdit issue with PvPArena

### ISSUE THREAD

**Issue by 0x1x2** [slipcor/pvparena#271]
Hello!

When I play a game in PvPArena, the nametag in the tab list for my name and all people in the game has their prefixes removed. However, people who didn't play in the PvP arena still saw our prefixes. 

Server is on 1.10.2.

Plugins:

ScoreboardHotfix, SimpleBroadcast, Languages, MythicLib, PlugMan, CustomPolls, Spartan, DeluxeTags, DupePatch, VKAutoPickup, ChatControl, FastAsyncWorldEdit, Vouchers, PermissionsEx, FeatherBoard, mcMMO, Lores, PlaceholderAPI, VoidWorld, VKBackPack, NametagEdit, Lockette, MyItems, OldCombatMechanics, TitleAPI, MultiSkyWars, VoxelSniper, LightAPI, WorldEdit, OpenInv, PacketListenerApi, BuycraftX, Votifier, VPNGuard, FastAsyncRedstone, MysteryBoxes, SQLibrary, CustomVillageTrades, Vault, PlayerPoints, ChestCommands, StaffPlus, MyWarp, MessageAnnouncer, Citizens, OnTime, ProtocolSupport, ObsidianAuctions, PerWorldInventory, WorldGuard, AuctionHouse, ASkyBlock, Essentials, SafeTrade, KitAdder, CS-CoreLib, EnjinMinecraftPlugin, RPGItems, NoFlyZone, ViaVersion, CommandNPC, QuickSell, BlockVersion, CompatNoCheatPlus, SilkSpawners, Multiverse-Core, ProtocolLib, Shopkeepers, ServerListPlus, MiniaturePets, ChestShop, EssentialsSpawn, CustomTab, HeadsPlugin, NoCheatPlus, LibsDisguises, eZProtector, HeavySpleef, Signs, CraftBook, HolographicDisplays, PhatLoots, ServerSigns, ShopGUIPlus, pvparena, mcMMOAction, CrateReloaded, UltraCosmetics, HeadsInventory, ProtectionLib, PvPManager, MythicMobs, FurnitureLib, FurnitureMaker, WorldGuardExtraFlags, MobStacker2, DiceFurniture, ProVotes, TokenEnchant, DeluxeChat, PrisonMines, EnchantmentBook, EBChance, Skript, SkStuff, skUtilities, skRayFall, SkQuery, Skellett, Umbaska, DailyBonus, LeaderHeads, ProQuests, ProQuests-Packages, BossShopPro, TrickyShops, ThirdCurrency, Item2Chat

**Comment by slipcor** [comment]
Can you show me a picture of how it looks before joining and how it looks after joining?

**Comment by 0x1x2** [comment]
http://imgur.com/a/GHxJu

Screenshots of tablist before and after joining an arena.

Other people still see the prefix though (like in Figure A).

**Comment by 0x1x2** [comment]
Hi - it's been a week... anything I'm doing wrong here?

**Comment by slipcor** [comment]
Sorry I have been busy with releasing a video on youtube. I did try to find ways to fix it. I will try something today!

**Comment by slipcor** [comment]
Please try this build, it might work :)

https://ci2.craftyn.com/job/PVP%20Arena/lastSuccessfulBuild/
