### ISSUE TITLE
Allow colorcodes in language file

### ISSUE THREAD

**Issue by 0x1x2** [slipcor/pvparena#272]
Hi!

PvPArena has been an amazingly customizable plugin in everything so far.

Except the language file.

My server uses light gray files for server messages, and the plugin's yellow and white harshly contrasts with it.

Can you please let us add colorcodes to the language file, please?

**Comment by slipcor** [comment]
You already can, with the character & (ampersand) you can use color :) if you find a place where this does not work please inform me. I will do a quick search through the plugin but there SHOULD be no hard coded yellow and white

**Comment by 0x1x2** [comment]
Tried to change the global prefix to &aArena and it just removed the entire setting in the config?

**Comment by slipcor** [comment]
@0x1x2 you might have to put single quotes around the prefix, if they are not there yet:

prefix: 'something'
