### ISSUE TITLE
Elytra in Class kit does not spawn

### ISSUE THREAD

**Issue by nunavailabul** [slipcor/pvparena#273]
I created an airsupport class with an Elytra, but when the player clicks the sign they do not get their elytra.

Spigot 1.11.2

**Comment by slipcor** [comment]
This is a strange issue, I have no idea why but for some reason it is stored as empty in RAM - restarting the server fixed it on my test server :)

**Comment by nunavailabul** [comment]
Tried that - any ideas what I might be doing wrong?

**Comment by slipcor** [comment]
Can you www.pastebin.com your config? I am currently debugging what is going on

**Comment by slipcor** [comment]
I am not sure why this is necessary but somehow spigot broke itemstack handling, and the fix, for now, is being compiled right now

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena/ :) #273 should fix it and with a proper restart it should work!

**Comment by nunavailabul** [comment]
no joy - still no Elytra - but the dump suggests that it thinks I have one.


**pvparena/config.yml** http://pastebin.com/j3MWQtLA
**pvparena/arenas/tdm.yml** http://pastebin.com/qRC73mJN  
**pvparena/dumps/_Sandbag_.yml** http://pastebin.com/Mz4Zz789

**Comment by slipcor** [comment]
can you try giving it as a regular item, not in the armors?

But to be clear, on my test server, it worked.... I am not sure how this can be oO

**Comment by nunavailabul** [comment]
That works - just doesn't work if you equip and save.  TY Slipcor.

**Comment by slipcor** [comment]
If this build does not fix it for you, please update Spigot - it seems that some of the last commits, they changed something that - together with this commit - did fix it on my test server. I actually have recorded this and will go through the footage to verify that I:

* did add this commit
* compiled and tested -> did not work
* some bugs appeared like item duplication (the last armor item was duplicated as storage/hotbar item)
* updating spigot fixed it - together with the fixes and debugs I made

**Comment by nunavailabul** [comment]
am I downloading this from the spigot page?

**Comment by slipcor** [comment]
No I did not yet update the spigot page, here is the latest version:

https://ci2.craftyn.com/job/PVP%20Arena/
