### ISSUE TITLE
Player is not teleported out of arena upon kick

### ISSUE THREAD

**Issue by 0x1x2** [slipcor/pvparena#274]
Title says all.

When a player is kicked with the Essentials /kick, upon relogging he will stay in the arena instead of being at the lobby (place where he clicked the sign).

Server is on 1.10.2.

Plugins: ScoreboardHotfix, SimpleBroadcast, Languages, MythicLib, PlugMan, CustomPolls, Spartan, DeluxeTags, DupePatch, VKAutoPickup, ChatControl, FoodMC, FastAsyncWorldEdit, Vouchers, PermissionsEx, FeatherBoard, mcMMO, FoodMCInjector, Lores, PlaceholderAPI, VoidWorld, VKBackPack, NametagEdit, PandaWire, Lockette, MyItems, OldCombatMechanics, TitleAPI, MultiSkyWars, VoxelSniper, LightAPI, WorldEdit, OpenInv, PacketListenerApi, BuycraftX, Votifier, VPNGuard, MysteryBoxes, SQLibrary, CustomVillageTrades, Vault, AcidRain, PlayerPoints, ChestCommands, StaffPlus, MyWarp, MessageAnnouncer, Citizens, OnTime, ProtocolSupport, ObsidianAuctions, PerWorldInventory, WorldGuard, AuctionHouse, ASkyBlock, Essentials, SafeTrade, KitAdder, CS-CoreLib, EnjinMinecraftPlugin, NoFlyZone, ViaVersion, CommandNPC, QuickSell, BlockVersion, CompatNoCheatPlus, SilkSpawners, Multiverse-Core, ProtocolLib, Shopkeepers, ServerListPlus, MiniaturePets, ChestShop, EssentialsSpawn, CustomTab, AreaShop, HeadsPlugin, NoCheatPlus, LibsDisguises, eZProtector, HeavySpleef, Signs, CraftBook, Item2Chat, HolographicDisplays, PhatLoots, ServerSigns, ShopGUIPlus, pvparena, mcMMOAction, CrateReloaded, HeadsInventory, ProtectionLib, PvPManager, MythicMobs, FurnitureLib, FurnitureMaker, WorldGuardExtraFlags, MobStacker2, DiceFurniture, ProVotes, TokenEnchant, DeluxeChat, PrisonMines, EnchantmentBook, EBChance, Skript, SkStuff, skUtilities, skRayFall, SkQuery, Skellett, Umbaska, DailyBonus, LeaderHeads, ProQuests, ProQuests-Packages, BossShopPro, TrickyShops, ThirdCurrency

**Comment by slipcor** [comment]
Thanks for the elaborate list of plugins. I hope that it is not a compatibility issue but an issue in my player kick->leave handling. Please check the latest version, it should be OK there.

**Comment by 0x1x2** [comment]
Alright, will try out the new test build

**Comment by 0x1x2** [comment]
Wait - where do I find the latest test build again .-.

**Comment by Oruss7** [comment]
https://ci2.craftyn.com/job/PVP%20Arena/

and modules are here: https://ci2.craftyn.com/job/PVP%20Arena%20Modules/
