### ISSUE TITLE
Scoreboard/Arenaboards not able to load?

### ISSUE THREAD

**Issue by Smithers09** [slipcor/pvparena#275]
I haven't been able to make the signs word in the arena, even after downloading both arenaboards.md and scoreboard.md - I've put both files in the mod folder of PVParena but to no avail?  Is it no longer working?

![screen shot 2017-02-07 at 6 20 03 pm](https://cloud.githubusercontent.com/assets/16909717/22719310/1aa5fabc-ed62-11e6-851a-1b9da63908ab.png)

**Comment by slipcor** [comment]
you do not need to download the "md" files, those are the documentation files, you need the "jar" files. As I do not know your server version, I will link you to my web page: http://slipcor.net/index.php?page=plugins

You need to click the "files.zip" link next to your version's "PVP Arena (files)" - then extract the arenaboards jar and put it in the mod folder.

Scoreboards are included in the main plugin as of version 1.3.3 - so you do not need to add a module for them

**Comment by Smithers09** [comment]
Attempting to make it work now.  Also, thank you for the feedback so quickly.  So much appreciated!

One last question - when I join my server, it is always saying this
![screen shot 2017-02-07 at 8 47 43 pm](https://cloud.githubusercontent.com/assets/16909717/22722811/b682b6e6-ed76-11e6-8e07-4a0077af5ccd.png)

Any idea how to turn off the alert?

**Comment by slipcor** [comment]
yeah I am waiting for some feedback before I release the version you are using as official, so this is a warning that your build is WIP :D

**Comment by Smithers09** [comment]
Ah, so if I rollback I'd be okay?  Arenaboards doesn't seem to be working with the signs with this version.  I'm also only at 1.10 for Minecraft

**Comment by slipcor** [comment]
Oh btw this message is only for OPs soooo I hope it is okay, you can set the "mode: both" to "mode: download" then it will only announce when it actually updated the plugin.

Oh no need to rollback, the latest versions will support 1.10. if it is not working for you it has to be a setup issue. did you follow the setup at https://github.com/slipcor/pvparena/blob/master/doc/mods/arenaboards.md ? 

You need to place the sign NOW when the module is added to the plugin AND activated for the arena (!)

**Comment by Smithers09** [comment]
Shoot.  When I do the /pa install, it says there's an error.  Can't make it to the next step, although I did try it with one of the arenas and it said arenaboards set to true.

**Comment by slipcor** [comment]
Welp, can you check your server log? It will contain the error so I can take a look at it.

**Comment by Smithers09** [comment]
Goodness, thank you so very much.

![screen shot 2017-02-07 at 9 31 57 pm](https://cloud.githubusercontent.com/assets/16909717/22723576/e3f8cad8-ed7c-11e6-82e6-f4b720657bd3.png)

**Comment by Smithers09** [comment]
This is the only error that's been kicked out

**Comment by slipcor** [comment]
Yeah. I need more than that, there have to be several lines in the log file. You are not in the log file, the log file is not colored :P

Please www.pastebin.com the part where this error happens. As soon as I see the lines involved I can fix this :)

**Comment by slipcor** [comment]
@Smithers09 hi?

**Comment by slipcor** [comment]
by the way it looks like that the plugin "ScoreboardStats" is causing this error, not PVP Arena :)
