### ISSUE TITLE
Plugin breaks after end.

### ISSUE THREAD

**Issue by aaroonung** [slipcor/pvparena#276]
After players join my FFA arena and lose their lives they dont get teleported out and dont get their items back. Also the players are unable to leave the arena with /pa leave. This is resolved by me doing a full reload or restart.
http://pastebin.com/XptL1msr
http://pastebin.com/kS37Zezm

**Comment by slipcor** [comment]
Version #240 might fix this - I wonder how this happens but that is not important for now, I am working on a proper rewrite, this has to do for now :D

https://ci2.craftyn.com/job/PVP%20Arena/lastSuccessfulBuild/artifact/target/pvparena.jar

**Comment by aaroonung** [comment]
Thanks for the quick reply!

**Comment by slipcor** [comment]
You were lucky I saw the email, I am heading to bed xD if it didnt work I will check it again tomorrow, can you leave a pastebin of your config in this case so I can reproduce the error?

**Comment by aaroonung** [comment]
Config -http://pastebin.com/MS1U3knj
Arena -http://pastebin.com/fERe95vz

**Comment by slipcor** [comment]
@aaroonung so my build did not fix this? I moved on to Spigot 1.11, did you also do that? Because if not I have to get you a special build :P

**Comment by aaroonung** [comment]
Yes, your build fixed it thanks. Also I moved to 1.11 too :p

**Comment by slipcor** [comment]
Awesome, thanks for the feedback!
