### ISSUE TITLE
Command to reload language file so you don't have to restart the server to make language adjustments.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#280]
Since you can reload individual arena configs, why not the language file or main PA config?

**Comment by mibby** [comment]
@slipcor I think it is working as intended per a language change I made, then having it reflect the changed output. However, typing ```/pa reload ymls``` does not have any output that it reloaded the main config.yml or language file. May want to have some feedback either to the player or console.

**Comment by slipcor** [comment]
yes. let's leave it at that for now. v2.0 :D I will add a quick update for the yml reload
