### ISSUE TITLE
null display on player death

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#282]
Version 1.3.4.249

When player die, display null on chat (but no error, everything is ok).

That's just a cosmetic bug ^^

**Comment by slipcor** [comment]
please show where and when this happens.

* in global chat?
* in the arena chat?

**Comment by Oruss7** [comment]
in global chat, all goals where player dies. `leavedeath: false` if that's help you

**Comment by slipcor** [comment]
you know, the whole config would help, in case there is something interfering 📦 
Could it be some other plugin causing this? I literally did a test run with the latest build and I had none of those issues. Please link your config so I can try to cause this bug with your settings

**Comment by Oruss7** [comment]
I will try to my test server without plugin, I come back after

**Comment by Oruss7** [comment]
My apologies. That's denizen plugin who display null. What event are you fire please ??

**Comment by slipcor** [comment]
I fire? erm....

PAGoalEvent
PALeaveEvent
PAWinEvent
PAEndEvent
PALoseEvent
PAJoinEvent
PAPlayerClassChangeEvent
EntityRegainHealthEvent
PAStartEvent
PATeamChangeEvent
PADeathEvent
PAKillEvent
NCBLoadEvent
