### ISSUE TITLE
Feature Request - ChestFiller-like module for tiered random rewards.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#288]

**Comment by mibby** [comment]
Bump. Could even be as simple as defining 3 different 'fill' chest locations and have it so it pulls from the first chest the most likely, second chest location 50% as likely, and then third chest location 25% as likely (or something) if we wanted to keep it simple. This would allow a pseudo tiered item pull rarity and allow the ability to add more than a double chest amount of content to be used in an arena chest.

**Comment by slipcor** [comment]
why is this accepted? I have no clear idea of what you are asking :P

so ... it woudl be a mix of locations and location probability or tier and ... a tier-corresponding set of items?

**Comment by mibby** [comment]
No, not location based. A tier system so the items that are randomly pulled can be sorted by rarity (probability) of being in a chest. 

i.e.

Tier 1 - Super common drop chance.
- Stone weapons

Tier 2 - Uncommon items / drops
- Gold / iron weapons

Tier 3 - Rare & Legendary items / drops
- Diamond gear, golden apples, etc.

The way ChestFiller works now, you can only have 1 single doublechest location of items and those items are randomly selected to be filled in a chest. You can't define any sort of rarity of items.

**Comment by mibby** [comment]
Closing ticket. I personally no longer use this module so closing to reduce the possible work burden to implement / fix. Feel free to re-open if this is something you do want to implement.
