### ISSUE TITLE
Signs to automatise arena join

### ISSUE THREAD

**Issue by WyRe** [slipcor/pvparena#296]
I've not seen such a thing in documentation, but there exist? I mean, I would like to automatise the arena join using sings placed in my server lobby.

Thank you so much again.

**Comment by slipcor** [comment]
What do you mean "automatise" ? There are join signs, check the SpecialJoin module, but if you mean signs to start, stop, reset an arena, you might have to look into commandsigns or commandbutton plugins and use the given commands PVP Arena has:

/pa [arena] forcestart
/pa [arena] stop
/pa [arena] reload

**Comment by WyRe** [comment]
Yes, that was I was looking for, thank you so much :P
