### ISSUE TITLE
Beacon locations get set when setting up an arena region instead of toggling beacon setting mode.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#306]
Setting up a new KOTH arena using the beacon goal module, selection a region with a worldedit wand (wood axe) set a new beacon location when beacon setting wasn't toggled enabled.

**Comment by slipcor** [comment]
v1.3.4.289 - [Beacons] - only set beacons if we used the command

https://ci2.craftyn.com/job/PVP%20Arena%20GameModes/
