### ISSUE TITLE
[question] Making goals work

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#308]
Sorry for the questions, I cant seem to find updated Docs that explain everything, most docs are half written and don't explain everything!

- How do I get goals to actually work? I have created a team deathmatch, I want it so theres 2 teams, and they have to kill the other team 30 times to win, I also want there to be a timer set to 20 mins, so if they don't do it in that time it finihses the game.
- How do I get a GUI of Kills leaderboard and time left on screen?
- [bug?] I think this is a bug, for some reason, it will NOT teleport me into a game once I have joined a team and selected a class. Not OP, same rank as other players that work fine! Theres nothing special about my account. It just wont teleport me into the game, but it thinks im in the game as im able to fire arrows in the lobby etc.
We seem to have a LOT of issues with teleport, We use MoveCraft plugin which moves players on ships by teleport them fast, is there a way to disable the teleport cancel event?
- How can I display team colors in players? Having their name color above their head blue/red showing their team? I could easily do this if I could set their Group, wanted to know if there was a built in method, if not Ill use the Events trigger to put set them at a rank when the pick a class, and have classes specific to each team so then it knows what team colors to pick.
- How do I move/remove the Join signs? I cant break them?

**Comment by slipcor** [comment]
@FrozenBeard oh my god, dude, I totally did not see this - is this still relevant? :O

**Comment by FrozenBeard** [comment]
Yeah I didn't figure most out.
