### ISSUE TITLE
When game goes to start, Teleported into the arena for a half second then teleported into spectator?

### ISSUE THREAD

**Issue by BelleGoBelle** [slipcor/pvparena#310]
Hi! So I recently just downloaded this plugin and it works really good for my server, The only problem with it is that whenever a arena match tries to start, the players are teleported into the arena then teleported back.

I looked into console and saw this error:
[11:11:42] [Server thread/INFO]: [PVP Arena] Error: No team found!

But I set the region, the teams spawns and lounges. I'm really confused.

How can I fix this?

**Comment by Oruss7** [comment]
can we see your arena config file please ?

**Comment by BelleGoBelle** [comment]
Here's the config file for the Arena: https://pastebin.com/ap1BgjRj

**Comment by slipcor** [comment]
Interesting choice of a cylinder region - I hope you did this on purpose :)

It looks almost fine - but the cylinder region extends to x = -633

And this is the exact spawn point, too - this gets translated to -633.5 I guess (by minecraft :P)

And then the plugin thinks you are out of the region :) 

Try moving in the spawn points into the center 1 or 2 blocks

**Comment by BelleGoBelle** [comment]
I tried doing what you said, and it didn't work..
