### ISSUE TITLE
[bug] Scoreboards dousnt exist?

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#311]
https://github.com/slipcor/pvparena/blob/master/doc/mods/scoreboards.md

Its not in the files.zip and it seems like its the only addon to give a scoreboard!

**Comment by slipcor** [comment]
Oh ... I have to remove this - this has been added to the main game!

just /pa [arena] set scoreboards true

or set the uses.scoreboards to true :)

**Comment by FrozenBeard** [comment]
God its so complex and time consuming to setup 1 arena... This is DAYS I have spent on it now.
Scoreboards should be on by default.
Maybe you need to include a bunch of configs with ALL options in them for examples. I think if you crated a bunch of configs with examples for all game types with all options available it might be a bit easier to find this.. there are no full docs...

**Comment by slipcor** [comment]
Good. Well. If you want something that reads your mind, I guess you have to ask someone else to make a plugin just for you :p

The more config options I add the more people will disagree on the default values of those. Many many servers do have their own scoreboards and do not want PVP Arena to mess with them ;)

I do have to include a config with all options? What else do you need than what you have, you have your whole config, that contains all things that you can set..

Maybe , if I find time and energy to do v2.0 I will add comments to the config but this is not supported by the bukkits YAML version --- and the config already is HUNDREDS of lines, this would double or triple the amount........

**Comment by slipcor** [comment]
And I have 24 modules and 10 goals (which is more than 10 ways to play, right? you can combine goals) so you can do the math how many configs I'd have to create - and maintain when I add or remove or change config settings/values/logic...

And no matter how many of those I created, I would always miss SOME people's configuration of goals. So you need to find your own way of doing this :)

**Comment by FrozenBeard** [comment]
How do I customise the look of the scoreboard? Is there a way to display the time left in a round in the scoreboard like most pvp games do?

**Comment by slipcor** [comment]
No, this is not an option right now

**Comment by FrozenBeard** [comment]
oh right, there are Grammatical errors and the colors are disgusting. 
maybe support a third party thats made some good looking scoreboards? or just have the words in teh language file so I can at least change the colors and put capital letters for the teams.

**Comment by slipcor** [comment]
Grammatical errors? It displays the arena name and player names, what is there to do grammar wise?

You can rename the teams if that is a big issue for you. I suggest replacing all instances in the config of "blue" and of "red" - or whatever you did name your teams :P

The arena name is changeable by renaming the yml file too - for safety I advise to do this when the server is not running :)

**Comment by slipcor** [comment]
And you can change the team colors in the config, too ^^
