### ISSUE TITLE
[BUG]! If you chagne a spawn location you have to REBOOT THE SERVER

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#312]
When you change the player spawn locations the only way for it to actually work is if you reboot the ENTIRE SERVER.

**Comment by slipcor** [comment]
no that's not correct ^^I have videos of me showing you that you do not have to restart, the points are loaded every time when needed :P some goals or modules do require a restart though

**Comment by FrozenBeard** [comment]
Err yes it is. I moved my red spawn point 3/4 times, double checked the arena Configs to 100%. Make sure the new coords were set, they were but when you joined a game it would always use the old spawn. I did a pa reload too and nothing the only way to update the team spawn points is to reboot the entire server. Same bug for scoreboards.

**Comment by slipcor** [comment]
I tested it with the lounge spawn, I cannot imagine that the others are different, it is hard to test such things on your own but:

**/pa [arena] reload** reloads the config (and it did update the spawns for me, too)

So anyways I updated the plugin to allow on-the-fly spawn changing, technically speaking I forgot to remove the "old" spawn definition from the spawns/blocks list, so there were 2 fitting spawns, and the old got checked before?

**Comment by FrozenBeard** [comment]
Have a try with player spawns, thats where I got the issue :)

**Comment by mibby** [comment]
This is a problem? I always had spawns update correctly when reloading the config in-game. :o

**Comment by slipcor** [comment]
I am 100% sure they did not try to reload - it worked for me, instantly ;)

But as said, technically I "simply added" another spawn of the same name that already existed, it is inconsistent and fixed now

**Comment by FrozenBeard** [comment]
Now I think about it, I think I did /pa reload and not /pa reload arenaname. This isn't very clear in the documentation. would this matter? The docs need some serious work.

**Comment by slipcor** [comment]
No, this does not matter, it would even work better because "/pa reload" reloads globally (all configs and all arenas individually) - so I really do not understand why this did not work.
