### ISSUE TITLE
[request] EventActions ClassChange %class% parameter.

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#313]
Hello!
You added in the ClassChange event for EventActions, which is fantastic, but the issue is there is no way to know what class the player has picked! If we could please have %class% then we could set specific roles for that class! 

Thank you.

**Comment by slipcor** [comment]
done, you need to update your module, obviously ;)

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/

As per your request, the class should be accessible via %class% - please report back if this works as intended!

Documentation on this will be added

**Comment by FrozenBeard** [comment]
YOU ARE THE MAN! I will get testing now!

**Comment by FrozenBeard** [comment]
%class% does not seem to work at all, in message or in a command.
I updated all the files from the Jenkins supplied.

**Comment by slipcor** [comment]
Okay, several questions - that would have been answered, had you shared your config :P

Did you put the "event:" block at the very end of the config, or at least with NO ident before "event:" ?

And did you copy the "ClassChange" (caps matters!) because it was wrongly put as camelcase, the correct way to denote is:

"classchange"

So if you change this this has to work, update the config and /pa [arena] reload

If that does nto work, I need to see your config - because it worked on a test server I set up in a minute, it broadcasted my class change, and entered the class correctly :)

Oh and did you replace the files do /files or to /mods ? because the file in /mods is being read !

**Comment by FrozenBeard** [comment]
It's the same config I already shared on another ticket.
Here: https://pastebin.com/9C9ntkyz

1. yes, I know how to format the syntax for a yaml file, I'm not retarded, its at the end and the indentation is correct.
2. yes I figured out you messed up your wiki entry myself, trial and error helped me solve your issue with case documentation. I figured that out myself.
3. I already attempted a broadcast to make sure I was testing it correctly, it literally displays the %class% as that text on screen.

Are you 100% you uploaded the right file and the changes were made to the Jenkins?

**Comment by slipcor** [comment]
![grafik](https://user-images.githubusercontent.com/970122/28692981-28a7a8f8-7323-11e7-8f85-6c772e6df17d.png)

1. good job on not being retarded!
2. thanks for not reporting or pull requesting!
3. maybe you need to check that you got the right files? I just downloaded the latest modules from the jenkins link I gave you and this works on my end

**Comment by FrozenBeard** [comment]
haha thanks, although I do think i was dropped on my head as a baby, maybe thats why I cant get it to work.

**Comment by FrozenBeard** [comment]
As requested I re-downloaded the files.zip from https://ci2.craftyn.com/job/PVP%20Arena%20Modules/ 
Stopped the server, extracted them to /plugins/pvparena/files

http://i.imgur.com/BwfdRhW.png

what am I doing wrong then?

**Comment by slipcor** [comment]
Yeah, you put them in the /files folder - this is the folder where they initially get put **to be installed** - that means, files that are in there are not used **until** you **install** them - which you did for the ones that you are using, and once you do install them with /pa install [modname] they are being put inside the /mods folder, i.e. the file is moved

So you either have to use the /pa install [modname] again, or you have to move the files to /mods IF they are installed already - maybe /pa update [modname] would work too, not sure.

**Comment by FrozenBeard** [comment]
Oh Jesus, this is utterly bonkers system. Why not just reference the files already in /files, why this extra step for mods? That's just double the space for storage, and there is no way anyone could know to do this for updating, its literally stated nowhere. Each arena has a config option to enable/disable what you want, having a separate mods folder makes literally no sense.
The backend design of this plugin is utterly bonkers.

**Comment by slipcor** [comment]
You are the first one in years to complain about that. The reason for the separation is a double check to make sure that you do not mess with loaded jar files, this can lead to all sorts of issues, so I added this extra step of INSTALLING a module after you pulled it in, so it can be properly unloaded and re-loaded.

**Comment by FrozenBeard** [comment]
So how do I go about updating them then?
