### ISSUE TITLE
[bug] /pa reload ends the game twice

### ISSUE THREAD

**Issue by FrozenBeard** [slipcor/pvparena#314]
I setup EventActions to run a bcast on end game so I could see if it was working, so when I do /pa stop, it runs once as it should. But when I run /pa reload to reload the configs, it runs twice!
There is a bug with pa reload ending the game twice.
```
  end:
  - cmd<=>bcast game ended
```

**Comment by slipcor** [comment]
Thanks for this report, I found the duplicated stopping and removed one ^^
