### ISSUE TITLE
Leaderboard [java.lang.IllegalArgumentException]

### ISSUE THREAD

**Issue by falget** [slipcor/pvparena#318]
Hello, after create a global leaderboard, in the config.yml creates a string with "leaderboard: world,-1253,66,475,0.0,0.0", after that when server restart i get a message in console https://pastebin.com/VMHyzBKf and plugin disables or my arenas not work. If remove ",0.0,0.0" in the config, plugin wil work but when i recreate leaderboard will again be the same.

**Comment by slipcor** [comment]
Thanks for the analysis, I was able to fix this quickly because of your help :)

Sorry that it took me so long but I check github notifications several times a week and this issue did not get marked as unread :/

https://ci2.craftyn.com/job/PVP%20Arena%20Modules/
