### ISSUE TITLE
Question about events

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#320]
I'm contributor to depenizen, it's an add-on to denizen which supplied pvparena support.

I need to know if event **PALeaveEvent** is always throw when players win/lose or leave game ?
If not, can you list me all event which made player leave the arena (disconnecting, win, lose etc)

Thanks !

**Comment by slipcor** [comment]
Hey :) this is called when a player uses /pa leave

For ALL events (including /pa leave !) this event here is called:

https://github.com/slipcor/pvparena/blob/master/src/net/slipcor/pvparena/events/PAExitEvent.java

so when a player exits no matter the reason

**Comment by Oruss7** [comment]
thanks !
