### ISSUE TITLE
ChestFiller module no longer fills chests.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#321]
@slipcor Upstream spigot commit breaks backwards compatibility in how blockstates work for container updating if you weren't using the API correctly. This commit subsequently seems to breaks ChestFiller for me as it no longer updates chests with items in one of my arenas.

https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/19507baf8b7903427bc3efab7118de6e7c1c931e#src/main/java/org/bukkit/craftbukkit/block/CraftBlockEntityState.java

I propose release the current version as a final build for backwards compatibility, then bump dev builds to 1.12.1+ to correct and fix this issue with the latest api logic?

**Comment by mibby** [comment]
Upon further testing, ChestFiller seems to be broken in arenas that rely on single chests to be filled. Doublechest locations in other arenas get filled fine. So I'm assuming the BlockState change breaks how you set single chests with inventory contents or alternatively (though heavily unlikely), it is caused by the coordinates being negative in that arena.

**Comment by mibby** [comment]
Confirmed fixed as of https://github.com/slipcor/pvparena_modules/commit/febd72611930e712eaad5cc28c42fd6c956ce91b

**Comment by slipcor** [comment]
thanks for the heads up!
