### ISSUE TITLE
Giving the kit after tot time player joins a lounge

### ISSUE THREAD

**Issue by Zughy** [slipcor/pvparena#322]
Hello, I have quite a situation here and I don't know if there is an option I could edit to fix it (but I swear, I searched in the whole wiki :( )
I have this arena with a custom kit, so that when people join, they obtain their standard inventory. Moreover, I use denizen to remove just a couple items but I have to wait that the old items appear in the inv before run my code or... well, it doesn't work as players inventories have nothing but air.
I put a 3.2 seconds delay, still sometimes those items appear before that time, sometimes after.
Is there a way to remove this CD eventually? 
I use specialjoin module

**Comment by Oruss7** [comment]
you mix denizen and pvpArena ? Denizen catch event before pvparena. Maybe pvparena cancel your inventory tricks ... Why use denizen ? i don't really understand your needs.

**Comment by Zughy** [comment]
It's an RPG and I want to remove the player profile and the journal. Moreover the denizen `leavelobby` item, replacing it with the (denizen) `leave_arena` one (executing /pa leave). 
We're trying to remove commands and use items only

**Comment by slipcor** [comment]
3.2 seconds? that should be enough by 3 seconds - PVP Arena waits 3 to 5 ticks, which is 0.15 seconds to 0.25 seconds - I have no idea what else to do about this, because I can only do things in the realm of my plugin - maybe the players who have this issue do have client side lag?

No idea what thiese denizen items mean, what "CD" do you want to remove? what is CD in this context?

**Comment by Oruss7** [comment]
I 'm updating depenizen, an add-on for denizen to handle pvpArena events like joins, leave and exit: https://github.com/DenizenScript/Depenizen/pull/167

I'm using depenizen to wrap /pa commands.

**Comment by Zughy** [comment]
In the end I solved it creating a custome /give on denizen and adding the specialjoin module like this:
```
event:
  join:
  - cmd<=>replaceitem entity %player% slot.hotbar.6 air
  - cmd<=>replaceitem entity %player% slot.hotbar.7 air
  - cmd<=>replaceitem entity %player% slot.hotbar.8 air
  - cmd<=>dgive %player% leavearena_item 9
```
