### ISSUE TITLE
Question infected goal

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#325]
Hello Slipcor,

I have `    iplayerprotect: 0` param. What's that ?

**Comment by slipcor** [comment]
Oh wow this is undocumented :O

This is a "PlayerPrevention" flag for the infected players that you can set with:

/pa [arena] setprotect [type] {true|false}

if you omit the value, it will switch the value, it will then show you what the value is set to - 0 means nothing is protected. It basically restricts infected players from doing things - much like the region protections. Possible types are:

<pre>
     * BREAK - Block break
     * PLACE - Block placement
     * TNT - TNT usage
     * TNTBREAK - TNT block break
     * DROP - dropping items
     * INVENTORY - accessing inventory
     * PICKUP - picking up stuff
     * CRAFT - crafting stuff
</pre>

**Comment by Oruss7** [comment]
ok thanks
