### ISSUE TITLE
Feature Request - McMMO Support

### ISSUE THREAD

**Issue by Pawned** [slipcor/pvparena#327]
Amazing plugin, one thing my players are always requesting is McMMO support so that they don't lose levels when dying during a pvp battle.

**Comment by slipcor** [comment]
losing levels? Since when is that an issue :O

is there a permission to give or a flag you can set or have PVP Arena set for this not to happen?

There has to be a way to fix this as-is ^^

**Comment by Pawned** [comment]
If there is a way to fix it as-is I'll be happy to hear it :) but I couldn't see any way 

Basically, we have McMMO set to lose 1% of the McMMO levels upon death and we want to keep it this way, however we have introduced PvPArena as a fun way for players to PvP without worry but they do still lose McMMO levels when they die in the PvP arena.

As far as I know there are no ways to disable McMMO in a WorldGuard region or anything, which would solve the issue

I also just noticed that Towny takes money and also SavageDeathChest places death chests in the arena's, these are lesser issues but still a little annoying.

All vanilla stuff is fine, normal XP and items are returned after the fight.

Does PvPArena currently cancel the player death event? I feel like that would maybe solve the issues as it should theoretically stop these other plugins from doing anything.

**Comment by slipcor** [comment]
the player death event is sadly not cancellable, to my knowledge - but I do my best to account for this, if you have "preventDeath: true" in the arena config - which should be the default

for towny I know that you can set PLOTS to be of arena type!

can you ask the mcMMO people if they know a way to do this? temporary permissions, command, anything I can do in my plugin that does not include actually building a dependency?

**Comment by Pawned** [comment]
thanks for the reply, I've just found the following permission in McMMO which enables users to bypass the hardcore mode which would stop them losing the levels if they have this while in the arena: mcmmo.bypass.hardcoremode

**Comment by slipcor** [comment]
Awesome! Then you can give the players this permission with the TempPerms module :D

https://github.com/slipcor/pvparena/blob/master/doc/mods/tempperms.md

The game will automatically add these pemissions and remove them when you leave the arena or are kicked or whatnot.

These are temporarily, not by hooking into your permissions plugin, but by adding them to a specific "temporary pool" in the player permissions, spigot side, if you need help, give me a shout ^^

**Comment by Pawned** [comment]
Awesome thank you very much, I'll close this issue down and open another if I get any problems :)
