### ISSUE TITLE
Big bug with armor.

### ISSUE THREAD

**Issue by asvpxrocky** [slipcor/pvparena#328]
If player leaves the server while he is in arena, after he joins back and the game has ended, he gets permanent armor without having any actual armor on him. For example if he crafts diamond armor while in arena then puts the armor on him and leaves the game after he will join back he will have permanent diamond armor even if he dies/reconnects/goes to other worlds he will still have the stats from diamond armor.
https://gyazo.com/3038655bb876d090b4919b7ec4c3b708
In this screenshot you can see i have no armor on, but it shows 1 armor bar above my hearts, becuase i joined the game chose the class that gives me helmet and left the server, rejoined and now i got infinite armor. you can do this over and over again untill you are practically unkillable.

Maybe there is some way that you could make an option if you leave the server while in arena or lounge player automatically dies, maybe that would fix the issue.
Please help me to fix it ASAP.

**Comment by slipcor** [comment]
I am sorry, but I can not reproduce this error on a clean installation of latest Spigot 1.12.2 and latest PVP Arena.

I joined a game, crafted armor, equipped it, showed full armor, but no matter whether I rejoin when the game is counting down to end, or when it is done resetting, my armor level gets reset to nothing.

Could it be that you have some hacky plugin installed that deals with armor enhancement / enchantment?

The stuff that I imagine being to blame for it (NBT Tags) is something I never touch, for exactly this reason. These values persist if you do not remove them properly , and I am very sure I am not using them, and removing everything I add where I can.

Good luck! But .. I feel I cannot help you. Do you see any errors when a person doing this disconnects? stacktraces, warnings, anything?
