### ISSUE TITLE
checkpoint: message for winner ?

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#331]
Hello,

I use Checkpoint goal. When player reach lastest checkpoint, the game finish with 3, 2 ,1. Without any victory message or game finished message ...

https://pastebin.com/udacjtaC

Thanks

**Comment by slipcor** [comment]
Please re-create the arena with a FREE setup, so it is a free for all, not a teams arena.

You did not get a message because the team arena has no language setting for "player has won" only for "team has won" :)

**Comment by Oruss7** [comment]
Ahhh okay. Thank
