### ISSUE TITLE
checkpoint numbers

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#332]
Hello,

I use checkpoint goal and don't really understand why the checkpoint 0 have no message and other have `<player name> reached checkpoint #<cp number -1>/<max>`. Why made -1 on checkpoint number ?

Thanks

**Comment by slipcor** [comment]
Not sure why my logic was this way, but I fixed it, I think. It shows the first one too and it 1, 2, 3, 4 instead of 0, 1, 2, 3
