### ISSUE TITLE
bug betterclass: effects don't set when player die and respawn

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#334]
Hello,

I havn't errors in logs. Arena settings don't change, before working great, now bug.

pvpArena 1.3.4.293 (latest with latest module better class 1.3.4.284)

https://pastebin.com/nuAM70eS

Thank you.

**Comment by slipcor** [comment]
well then I will have a look into this. If Spigot broke this and I cannot find how they broke it .....

Let's just hope that is not the case

**Comment by slipcor** [comment]
![grafik](https://user-images.githubusercontent.com/970122/34184496-5c6f82a4-e520-11e7-96fa-ce7e9043a132.png)
I think I need your full arena config. For me it works just fine. I added a SLOW:1 effect on one class, and on respawn, I do get it back just fine :/ 

and if you could do a debug that would help, too:

/pa debug all

have a player get killed and their effects not reappearing

/pa debug off

You know the drill, right? :D

**Comment by Oruss7** [comment]
config: capture the flag: https://pastebin.com/i5tVRdaU
debug: https://pastebin.com/NcNkXa7B

**Comment by Oruss7** [comment]
Duplicate of https://github.com/slipcor/pvparena/issues/338

**Comment by Oruss7** [comment]
Fix by https://github.com/slipcor/pvparena_modules/pull/20
