### ISSUE TITLE
NBT data of items / inventory contents are not properly saved to player dump on logout and relog like MobArena.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#339]
PVPArena - v1.3.4.296
Paper dev 1290 (Spigot 1.12.2)

@slipcor Ran across this issue when players were reporting their in-game hats being reset back to a diamond shovel.

When players join an arena and disconnect from the server while still inside the arena, upon logging in and receiving their inventory contents back, the NBT data for various items is lost and reset back to default. Joining an arena and leaving normally via ```/pa leave``` functions fine. It only breaks when you leave an arena unnaturally via disconnecting and rejoining.

Example 1;
* Player has an in-game hat equipped outside arenas. (A diamond shovel with a specific damage value and unbreakable NBT flag set - shown as a custom item / hat via resource pack loaded but the underlying item is a diamond shovel with a damage value and unbreakable tag.)
* Player joins an arena.
* Player disconnects from the server.
* Player reconnects to the server, no longer inside the arena but has his original "outside" inventory contents back.
* Player's hat has reset back to a diamond shovel with no damage value or unbreakable NBT tag.

Example 2;
* Player has colored leather boots equipped outside the arena.
* Player joins an arena.
* Player disconnects from the server.
* Player reconnects to the server, no longer inside the arena but has his original "outside" inventory contents back.
* Player's leather boots are no longer colored.

Reproduction steps;
* Join an arena. (/pa CTF)
* Log out / disconnect from the server while inside the arena.
* When you reconnect / log in again, the item durability / nbt data is reset. Players who reconnect are not brought back inside the arena and their inventory should be properly restored. 
* Joining and leaving normally via commands, no items are reset or lost. Only when disconnecting while inside an arena and rejoining the server thereafter is the item reset / broken by PA.

**Comment by mibby** [comment]
Possibly related to inventory snapshot not preserving NBT data of the items.

**Comment by mibby** [comment]
@slipcor Would it be too much to ask you to come back to fix this one problem? I miss you. :(

PerWorldInventory causes too many problems with inventory loss and duping with all the delays in place. It would be easier if PA could just properly clone the NBT data of all items in the inventory to the inventory dump.

**Comment by mibby** [comment]
😢

**Comment by Oruss7** [comment]
I'm reading https://github.com/Gnat008/PerWorldInventory/blob/master/src/main/java/me/gnat008/perworldinventory/data/serializers/InventorySerializer.java. Maybe we can re-use this code to serialize/deserialize inventories with nbt data.

**Comment by mibby** [comment]
@Oruss7 What about copying how MobArena preserves the inventory dump?

**Comment by slipcor** [comment]
Maybe this does it? :P https://github.com/slipcor/pvparena/commit/9b74b0e5749b6ae55f33db40fe8df1cf3e799987

**Comment by slipcor** [comment]
like this? https://github.com/slipcor/pvparena/commit/9b74b0e5749b6ae55f33db40fe8df1cf3e799987

**Comment by mibby** [comment]
@slipcor NBT data confirmed seems to be fine now. Disconnected after joining an arena, then reconnected to the server. The item NBT is still preserved instead of turning into a basic shovel. Thanks!
