### ISSUE TITLE
NBT Rewards

### ISSUE THREAD

**Issue by WeasomeKarma** [slipcor/pvparena#341]
Is it possible to have rewards include NBT data like lore and names?

**Comment by slipcor** [comment]
I am a bit out of the loop. So feel free to play around with this:

/pa [arena] set rewards INVENTORY

You should prepare your inventory to only include stuff you want to give as rewards [so strip your armor or it will be added, too ;) ]

This should support basic things like lore, description name, book contents, dye color, etc.

It will not include NBT Data like attributes, or custom NBT values

**Comment by WeasomeKarma** [comment]
Awesome that is more than good enough for me, thank you!

So far this mod is amazing, and more amazing yet is you're quick replies for helping me which I am very grateful for, but there is one thing I'd like to say. I feel like a few of these issues I've encountered would be avoidable if they were documented more (perhaps ur working on that if so ignore me) because I spent roughly 20 mins of skimming the wiki and I don't think I would've figured out how to do  anything I asked so far without asking.

Keep up the good work!

**Comment by WeasomeKarma** [comment]
Actually I still have an issue, when I use the command you gave me I get:

Invalid argument type: null is no property of item

not sure what that could mean

**Comment by WeasomeKarma** [comment]
Mmmm its lowercase inventory. I looked through the source code for the set command. "set hand" works nicely too

**Comment by slipcor** [comment]
okay but that is only one item, I assumed you wanted more :) 👍

**Comment by slipcor** [comment]
I hope you don't encounter many more bugs because I actually am no longer developing PA :/
