### ISSUE TITLE
Dominations arena broken

### ISSUE THREAD

**Issue by Joseph0430** [slipcor/pvparena#359]
I am running the latest stable version, and every time i set the victory condition to dom and set the flags, the flags won't work and i will be stuck in the arena fighting forever. I was able to escape by deleting the arena though. Is there any better tutorial to set up domination that the currently available one?

**Comment by Oruss7** [comment]
Hello Joseph,

Please open an issue here: https://github.com/Eredrim/pvparena/issues

And precise your PA version and spigot version. 
Share your arena config file can be nice too.

Thanks

**Comment by slipcor** [comment]
Thanks for forwarding them, I did not see a notification of HIM, only of your comment. Weird oO
