### ISSUE TITLE
Powerups don't spawn on arena

### ISSUE THREAD

**Issue by XMCaster** [slipcor/pvparena#361]
PVP Arena version 1.15.0-SNAPSHOT-b323
Powerups version 1.14.1-SNAPSHOT

Arena config in attach.

Powerup "Heal" don't spawn at spawnpoint powerupX.

[CTFArena.txt](https://github.com/slipcor/pvparena/files/4666925/CTFArena.txt)

**Comment by Oruss7** [comment]
Hi @XMCaster, please open issue here: https://github.com/Eredrim/pvparena/issues
It's the main developer now. Slipcor is the original but doesn't have time anymore.
Thanks.
