### ISSUE TITLE
[Idea] - New module / gamemode. Falling anvils.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#62]
Polar opposite to the gamemode TNTRun / block dissolve module.

Have Anvils spawn randomly on a Y level above the battlefield. If players are hit by a falling anvil, they are killed. To avoid players jumping on anvils, have the anvils despawn after so many ticks or fall 2-3 anvils stacked on top of each other. Perhaps to add more spice to the gamemode, have anvils despawn the blocks they land on so you can have players trying to avoid holes that lead into the void or lava?

**Comment by slipcor** [comment]
okaaaaaaay we will check this out xD

**Comment by slipcor** [comment]
https://github.com/slipcor/pvparena/blob/master/doc/mods/fallinganvils.md

have fun :D

**Comment by mibby** [comment]
Few issues with the falling anvils module. 

- Various anvils did not despawn / clean up after themselves on arena end. I assume because the anvil state changed when it took damage on the fall. 
- Some anvils broke on the fall and turned into drops.

Few potential 'quality of life' enhancements.

- Config setting to define what block the anvil can spawn above. I.e. only spawn above glass for a glass floor and not fall in-between holes in the glass. Would also prevent anvils from spawning on top of each other if there is already an anvil on the block pending despawn/cleanup.
- Config setting to define a specific battlefield region the anvils can actually fall from. So it isn't checking / spawning across every block within a huge battlefield region selection.
- Config setting to define how high the anvils spawn from.
- Death definition for FALLING_BLOCK?
```
16.05.26 13:15:03 [INFO] [PA-debug] [p:player]972 return a damage name for : FALLING_BLOCK
16.05.26 13:15:03 [INFO] [PA-debug] [player]972 damager: null
16.05.26 13:15:03 [INFO] [PA-debug] 972 MSG: FIGHT_KILLED_BY
16.05.26 13:15:03 [INFO] [PA-debug] 973 @all: §9player§e has been killed by the Void!
```

**Comment by slipcor** [comment]
yes. I am literally keeping track of the Entity that is the anvil. If this does randomly not work (the state change should not the entity oO) - I am not really willing to add the rest of things and fix everythingn when the main issue remains that Bukkit loses track of the anvil entities and still does not remove them.

Or would "removing all anvil blocks" be a possibility to offer? Would only work on maps that contain no anvils as scenery/props, but that's that xD

**Comment by mibby** [comment]
Removing all anvils wouldn't fix the underlying issue of anvil tracking being lost when the anvil state changes. It would be moreso a workaround and one that would kill anvils used for aesthetic decoration on the map. Unless you could define a specific battlefield region for anvils to only fall in and cleanup. 

But then again the problem still exists, how would you cleanup anvils that aren't removing themselves when their state changes on taking damage? It would leave anvils in the battlefield that players could stand on until the 'all anvil' cleanup runs on battlefield end. It wouldn't make sense to periodically clean-up all anvils every certain amount of tickets because then still falling anvils would magically disappear rather than despawn some time after hitting the ground.

I think if the tracking issue can't be fixed, this module should probably be terminated.

**Comment by slipcor** [comment]
Agreed. Good bye, Anvils :)
