### ISSUE TITLE
[Bug] - Remaining two players dying at the same time, Error: No player found!

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#64]
@slipcor 

Remember this?
https://github.com/slipcor/pvparena/commit/ee9c9506cc1e140d23f111eb3a6f9072e9f0ab1d#diff-e3c837e03b399020ab382590206ecbd6R163

I assume it is still occurring because you need to set arena.realEndRunner for all the goals, not just TDM?

**Comment by mibby** [comment]
@slipcor Re-opening ticket. Still seems to occur when two players die at the same time. D:

```
[11:20:18] [Server thread/INFO]: [Run] Error: 
[11:20:18] [Server thread/INFO]: [Run] Error: 
```

PVPArena dev build 550.

**Comment by slipcor** [comment]
Well I think as this does not throw an error and only seems to be a warning message, I'll just remove it and then we're done :D

**Comment by mibby** [comment]
Marked as fixed. Can't reproduce.
