### ISSUE TITLE
BlockRestore and Fire

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#75]
Hallo,
I have block restore actived but pvpArena don't extinguish fire before restore ...
So fire burn block during the restore ><

Tchuss,

**Comment by largo7** [comment]
Worldedit don't extinguish fire when backup the arena ... How remove fire automatically ?

**Comment by slipcor** [comment]
really? Worldedit should replace the fire with air - it worked for me, I'd say. I have seen people building pirate ships and then burning them, and PA fixes the fire with WE replacing the fire with "air" :)

**Comment by Oruss7** [comment]
Yes, that's always my fault. It's working now with world edit. I close this issue
