### ISSUE TITLE
[FEATURE] Enhancements / Mods / Startfreeze

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#79]
Hi,

I use StartFreeze for my hunger game arena. I would  like have counter please.

Example :
[FREEZE PLAYERS]
10
5
4
3
2
1
[UNFREEZE PLAYERS]

and an other idea : can you put player speed to 0 instead of check player movement ? (Reduce lags)
(You can test speed with essentials : /speed walk 0)

Thanks for Developping this amazing plugin.

**Comment by slipcor** [comment]
hahaha I imagine people sitting there and waiting for 60 seconds. Wow xD

Yeah I will add that!

**Comment by Oruss7** [comment]
note : '/speed walk 0' players can jump (and so move) ^^'

**Comment by slipcor** [comment]
mhhh you mean people can do that command and then they can move?

**Comment by Oruss7** [comment]
this command set walk speed to 0 but we can jump (in airs we can move).

**Comment by slipcor** [comment]
what kind of hack is this? I am confused oO

**Comment by Oruss7** [comment]
Yes, me too. That's a fun hack...

**Comment by slipcor** [comment]
this will be part of v1.3.0.558 version of StartFreeze :)

**Comment by slipcor** [comment]
https://ci2.craftyn.com/job/PVP%20Arena%20Modules/lastSuccessfulBuild/artifact/m_StartFreeze/target/
