### ISSUE TITLE
How to prevent build for only one team ?

### ISSUE THREAD

**Issue by Oruss7** [slipcor/pvparena#81]
I made a battleground with block destroy and time goals. Blue win with time end and red win with block destroy. 

Blue must protect the block, can build. 
Red have TNT and can't build. 

Please, tell me how make to prevent red build without blue ?

Thanks

**Comment by slipcor** [comment]
no idea, I did not provide a way for this to work. There are no team permissions. Though that was planned, I don't see many reasons to continue developing.

**Comment by largo7** [comment]
Maybe disable drop and add some block in blue's classes so blue can place and both can destroy

**Comment by slipcor** [comment]
yeah that would work, you can allow placing specifically by whitelisting e.g. "blue blocks" and then allow everyone breaking :D oh wait but it would not help people killing the other team and then GETTING the blocks that are allowed to be placed :/

Mhhh maybe I soon have time to write together a more specific permission system that allows class and team distinction :)

**Comment by Oruss7** [comment]
:triumph:

**Comment by mibby** [comment]
Relevant ticket feature for this issue, assuming PlayerPrevention will cover build permissions for specific defined teams. https://github.com/slipcor/pvparena/issues/123

**Comment by Oruss7** [comment]
Closed, please see https://github.com/slipcor/pvparena/issues/123
