### ISSUE TITLE
[Bug] [Module BetterClasses] - Class permEffects do not persist if users change classes in-game.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#84]
If you change classes in-game via commands but don't die, you lose your current class potion effects when the duration ends and get the new class's effects. 

Example.
* I join CTF and pick the class Tank. 
* Tank is configured to have a permanent effect of slowness.
* I spawn in-game when the game starts. 
* I decide I want to change classes when I next die, so I type /pa -ac scout. 
* Scout is configured to have the permanent effect of speed.
* I do not die as tank.
* When my slowness effect is suppose to renew (to avoid running out since it is suppose to be a permanent effect) I get the scout effects instead.

Ideally what is suppose to happen is not get the new class's effects (or gear) until the next respawn, since I use the config option classSwitchAfterRespawn: true.

Possible fix - move the actual class change event to when the death/respawn happens and add an exception for when in lounge mode or if class switching is configured to be instant, not after respawn. 

Have modules check for class changes, and store the old class in a temporary set until death.

**Comment by slipcor** [comment]
yeah I reset all the things because that's the easy way to ADD more effects. I think I had issues trying to remove them one by one, something always stayed or had an NPE - with you back in action I might be able to debug this with you :)

**Comment by mibby** [comment]
Confirmed fixed.
