### ISSUE TITLE
[Enhancement] - Language string for in-game class changing output when configured to change class on next respawn.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#85]
Is it possible to change the grammar output to class switching in-game when it is configured to be on respawn instead of instant? Currently it says "You have switched to [nameofclass] class" - whereas it may make more sense to say something like "You will change into [nameofclass] class on next respawn."

**Comment by slipcor** [comment]
that makes sense :)

**Comment by mibby** [comment]
Confirmed working.
