### ISSUE TITLE
[Bug] - Unknown cause: THORNS

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#87]
PVPArena dev build 550.

Noticed this in my console output.
```
[12:07:27] [Server thread/WARN]: [PVP Arena] Unknown cause: THORNS
[12:07:27] [Server thread/WARN]: [PVP Arena] Unknown cause: THORNS
```

Players were playing in my Infection arena. Goal infect. I have armor with the enchantment thorns randomly spawn with the module ChestFiller.

Arena config.
http://paste.ubuntu.com/9871400/

If I had to guess, pvparena couldn't track a player death or damage state caused by the enchantment thorns?

**Comment by slipcor** [comment]
damn enchantments
