### ISSUE TITLE
[Bug] [Module - RespawnRelay] - Players of opposite teams can damage each other in the relay respawn room.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#88]
I have a relay respawn room. If someone from red team and someone from blue team both die at the same time and get sent to the relay spawn location, they are able to hurt each other by punching until they respawn.

**Comment by slipcor** [comment]
that should not be possible! If that still is persistant atm can you do a quick debug? They should be of status DEAD and thus cancel the damage event :(
