### ISSUE TITLE
[Enhancement] TNT Run Goal !

### ISSUE THREAD

**Issue by largo7** [slipcor/pvparena#92]
When have some time, can you code a TNT RUN goal plz ?

Gravel, sands fall when player walk on, without tnt (lag) and pressure plate (lag more)

Thanks

**Comment by mibby** [comment]
Already exists. Block dissolve module + worldedit module.

**Comment by largo7** [comment]
I'm stupid, Thanks !

**Comment by largo7** [comment]
No documentation about ?
